# Generated by Django 4.2.11 on 2025-11-12 02:11

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0004_hotelextraservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reception', '0003_reservation_total_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('name', models.CharField(max_length=200, verbose_name='Acente Adı')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Acente Kodu')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='İletişim Kişisi')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Komisyon Oranı (%)')),
                ('commission_type', models.CharField(choices=[('percentage', 'Yüzde'), ('fixed', 'Sabit Tutar')], default='percentage', max_length=20, verbose_name='Komisyon Tipi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='Sözleşme Başlangıç Tarihi')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Sözleşme Bitiş Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='hotels.hotel', verbose_name='Otel')),
            ],
            options={
                'verbose_name': 'Acente',
                'verbose_name_plural': 'Acenteler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Varsayılan Komisyon Oranı (%)')),
                ('auto_calculate_commission', models.BooleanField(default=True, verbose_name='Otomatik Komisyon Hesapla')),
                ('sales_target_enabled', models.BooleanField(default=True, verbose_name='Satış Hedefi Aktif mi?')),
                ('default_target_period', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık'), ('yearly', 'Yıllık')], default='monthly', max_length=20, verbose_name='Varsayılan Hedef Dönemi')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_settings', to='hotels.hotel', verbose_name='Otel')),
            ],
            options={
                'verbose_name': 'Satış Yönetimi Ayarları',
                'verbose_name_plural': 'Satış Yönetimi Ayarları',
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('target_name', models.CharField(max_length=200, verbose_name='Hedef Adı')),
                ('target_type', models.CharField(choices=[('revenue', 'Gelir'), ('reservations', 'Rezervasyon Sayısı'), ('occupancy', 'Doluluk Oranı')], default='revenue', max_length=50, verbose_name='Hedef Tipi')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Hedef Tutar')),
                ('target_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hedef Sayı')),
                ('period_type', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık'), ('yearly', 'Yıllık')], default='monthly', max_length=20, verbose_name='Dönem Tipi')),
                ('start_date', models.DateField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(verbose_name='Bitiş Tarihi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_targets', to=settings.AUTH_USER_MODEL, verbose_name='Atanan')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to='hotels.hotel', verbose_name='Otel')),
            ],
            options={
                'verbose_name': 'Satış Hedefi',
                'verbose_name_plural': 'Satış Hedefleri',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['hotel', 'is_active', 'start_date'], name='sales_sales_hotel_i_3d521a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('report_date', models.DateField(db_index=True, verbose_name='Rapor Tarihi')),
                ('report_type', models.CharField(choices=[('daily', 'Günlük'), ('weekly', 'Haftalık'), ('monthly', 'Aylık'), ('yearly', 'Yıllık')], default='daily', max_length=20, verbose_name='Rapor Tipi')),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Toplam Satış')),
                ('total_reservations', models.IntegerField(default=0, verbose_name='Toplam Rezervasyon')),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Toplam Komisyon')),
                ('direct_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Direkt Satış')),
                ('agency_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Acente Satışı')),
                ('online_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Online Satış')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_reports', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_reports', to='hotels.hotel', verbose_name='Otel')),
            ],
            options={
                'verbose_name': 'Satış Raporu',
                'verbose_name_plural': 'Satış Raporları',
                'ordering': ['-report_date'],
                'unique_together': {('hotel', 'report_date', 'report_type')},
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('sales_type', models.CharField(choices=[('direct', 'Direkt'), ('agency', 'Acente'), ('online', 'Online'), ('walk_in', 'Walk-In'), ('corporate', 'Kurumsal')], db_index=True, default='direct', max_length=50, verbose_name='Satış Tipi')),
                ('sales_date', models.DateField(db_index=True, verbose_name='Satış Tarihi')),
                ('sales_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Satış Tutarı')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Komisyon Tutarı')),
                ('commission_paid', models.BooleanField(default=False, verbose_name='Komisyon Ödendi mi?')),
                ('commission_paid_date', models.DateField(blank=True, null=True, verbose_name='Komisyon Ödeme Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to='sales.agency', verbose_name='Acente')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='hotels.hotel', verbose_name='Otel')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to='reception.reservation', verbose_name='Rezervasyon')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to=settings.AUTH_USER_MODEL, verbose_name='Satış Personeli')),
            ],
            options={
                'verbose_name': 'Satış Kaydı',
                'verbose_name_plural': 'Satış Kayıtları',
                'ordering': ['-sales_date'],
                'indexes': [models.Index(fields=['hotel', 'sales_date', 'sales_type'], name='sales_sales_hotel_i_d53e70_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='agency',
            index=models.Index(fields=['hotel', 'is_active'], name='sales_agenc_hotel_i_296756_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agency',
            unique_together={('hotel', 'code')},
        ),
    ]
