# Generated by Django 4.2.11 on 2025-11-09 18:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenant_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Tur Adı")),
                (
                    "code",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Tur Kodu"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="URL Slug"
                    ),
                ),
                (
                    "transport_type",
                    models.CharField(
                        choices=[
                            ("bus", "Otobüs"),
                            ("plane", "Uçak"),
                            ("train", "Tren"),
                            ("ship", "Gemi"),
                            ("car", "Araba"),
                            ("mixed", "Karma"),
                        ],
                        default="bus",
                        max_length=20,
                        verbose_name="Ulaşım Türü",
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Kaç Gün",
                    ),
                ),
                (
                    "duration_nights",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Kaç Gece",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Tur Açıklaması"),
                ),
                (
                    "cities_to_visit",
                    models.TextField(
                        blank=True,
                        help_text="Virgülle ayrılmış şehir listesi",
                        verbose_name="Gezilecek Şehirler",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Tur Notları")),
                (
                    "max_adults",
                    models.IntegerField(
                        default=50,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Maksimum Yetişkin",
                    ),
                ),
                (
                    "max_children",
                    models.IntegerField(
                        default=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Maksimum Çocuk",
                    ),
                ),
                (
                    "child_age_min",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(18),
                        ],
                        verbose_name="Çocuk Yaş Minimum",
                    ),
                ),
                (
                    "child_age_max",
                    models.IntegerField(
                        default=12,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(18),
                        ],
                        verbose_name="Çocuk Yaş Maksimum",
                    ),
                ),
                (
                    "adult_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Yetişkin Fiyatı",
                    ),
                ),
                (
                    "child_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Çocuk Fiyatı",
                    ),
                ),
                (
                    "group_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Grup Fiyatı (10+ Kişi)",
                    ),
                ),
                (
                    "group_min_people",
                    models.IntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(2)],
                        verbose_name="Grup Minimum Kişi",
                    ),
                ),
                (
                    "campaign_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Kampanya Fiyatı",
                    ),
                ),
                (
                    "campaign_start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Kampanya Başlangıç"
                    ),
                ),
                (
                    "campaign_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Kampanya Bitiş"
                    ),
                ),
                (
                    "departure_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Tur Çıkış Saati"
                    ),
                ),
                (
                    "return_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Tur Dönüş Saati"
                    ),
                ),
                (
                    "price_includes",
                    models.TextField(
                        blank=True,
                        help_text="Her satıra bir madde",
                        verbose_name="Fiyata Dahil",
                    ),
                ),
                (
                    "price_excludes",
                    models.TextField(
                        blank=True,
                        help_text="Her satıra bir madde",
                        verbose_name="Fiyata Dahil Olmayanlar",
                    ),
                ),
                (
                    "hotels",
                    models.TextField(
                        blank=True,
                        help_text="Her satıra bir otel",
                        verbose_name="Konaklanacak Oteller",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tours/main/",
                        verbose_name="Ana Resim",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("published", "Yayında"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Öne Çıkan mı?"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Meta Başlık"
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(blank=True, verbose_name="Meta Açıklama"),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Meta Anahtar Kelimeler",
                    ),
                ),
                (
                    "view_count",
                    models.IntegerField(default=0, verbose_name="Görüntülenme Sayısı"),
                ),
                (
                    "reservation_count",
                    models.IntegerField(default=0, verbose_name="Rezervasyon Sayısı"),
                ),
                (
                    "rating_average",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Ortalama Puan",
                    ),
                ),
                (
                    "rating_count",
                    models.IntegerField(default=0, verbose_name="Değerlendirme Sayısı"),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ek Ayarlar"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tur",
                "verbose_name_plural": "Turlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Şehir Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                (
                    "country",
                    models.CharField(
                        default="Türkiye", max_length=100, verbose_name="Ülke"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Enlem",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Boylam",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
            ],
            options={
                "verbose_name": "Tur Şehri",
                "verbose_name_plural": "Tur Şehirleri",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TourDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("date", models.DateField(verbose_name="Tur Tarihi")),
                (
                    "adult_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Yetişkin Fiyatı",
                    ),
                ),
                (
                    "child_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Çocuk Fiyatı",
                    ),
                ),
                (
                    "group_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Grup Fiyatı",
                    ),
                ),
                (
                    "max_adults",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Maksimum Yetişkin"
                    ),
                ),
                (
                    "max_children",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Maksimum Çocuk"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_full",
                    models.BooleanField(default=False, verbose_name="Dolu mu?"),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_dates",
                        to="tours.tour",
                        verbose_name="Tur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tur Tarihi",
                "verbose_name_plural": "Tur Tarihleri",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="TourExtraService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Hizmet Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "price_per_person",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Kişi Başı Fiyat",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_services",
                        to="tours.tour",
                        verbose_name="Tur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ekstra Hizmet",
                "verbose_name_plural": "Ekstra Hizmetler",
                "ordering": ["tour", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="TourLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Lokasyon Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("domestic", "Yurt İçi"),
                            ("international", "Yurtdışı"),
                        ],
                        max_length=20,
                        verbose_name="Lokasyon Tipi",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
            ],
            options={
                "verbose_name": "Tur Lokasyonu",
                "verbose_name_plural": "Tur Lokasyonları",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TourRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Bölge Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome icon class",
                        max_length=50,
                        verbose_name="İkon",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
            ],
            options={
                "verbose_name": "Tur Bölgesi",
                "verbose_name_plural": "Tur Bölgeleri",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TourReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "reservation_code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Rezervasyon Kodu",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Müşteri Adı"),
                ),
                (
                    "customer_surname",
                    models.CharField(max_length=100, verbose_name="Müşteri Soyadı"),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="E-posta"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=20, verbose_name="Telefon"),
                ),
                (
                    "customer_tc",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="TC Kimlik No"
                    ),
                ),
                (
                    "customer_address",
                    models.TextField(blank=True, verbose_name="Adres"),
                ),
                (
                    "adult_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Yetişkin Sayısı",
                    ),
                ),
                (
                    "child_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Çocuk Sayısı",
                    ),
                ),
                (
                    "total_people",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Toplam Kişi",
                    ),
                ),
                (
                    "adult_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Yetişkin Birim Fiyat",
                    ),
                ),
                (
                    "child_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Çocuk Birim Fiyat",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ara Toplam"
                    ),
                ),
                (
                    "extra_services_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ekstra Hizmetler Toplam",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="İndirim Tutarı",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Toplam Tutar"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("confirmed", "Onaylandı"),
                            ("cancelled", "İptal Edildi"),
                            ("refunded", "İade Edildi"),
                            ("completed", "Tamamlandı"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("partial", "Kısmi Ödendi"),
                            ("paid", "Ödendi"),
                            ("refunded", "İade Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Ödeme Durumu",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "voucher_generated",
                    models.BooleanField(
                        default=False, verbose_name="Voucher Oluşturuldu mu?"
                    ),
                ),
                (
                    "voucher_pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="tours/vouchers/",
                        verbose_name="Voucher PDF",
                    ),
                ),
                (
                    "sales_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tour_reservations",
                        to="tenant_core.tenantuser",
                        verbose_name="Satış Elemanı",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="tours.tour",
                        verbose_name="Tur",
                    ),
                ),
                (
                    "tour_date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="tours.tourdate",
                        verbose_name="Tur Tarihi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tur Rezervasyonu",
                "verbose_name_plural": "Tur Rezervasyonları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Tur Türü Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="İkon"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3498db",
                        help_text="Hex color code",
                        max_length=7,
                        verbose_name="Renk",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
            ],
            options={
                "verbose_name": "Tur Türü",
                "verbose_name_plural": "Tur Türleri",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TourVoucherTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Şablon Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                (
                    "template_html",
                    models.TextField(
                        help_text="Voucher HTML içeriği", verbose_name="HTML Şablon"
                    ),
                ),
                (
                    "template_css",
                    models.TextField(blank=True, verbose_name="CSS Stilleri"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Varsayılan Şablon mu?"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
            ],
            options={
                "verbose_name": "Voucher Şablonu",
                "verbose_name_plural": "Voucher Şablonları",
            },
        ),
        migrations.CreateModel(
            name="TourVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "video_type",
                    models.CharField(
                        choices=[("youtube", "YouTube"), ("instagram", "Instagram")],
                        default="youtube",
                        max_length=20,
                        verbose_name="Video Tipi",
                    ),
                ),
                ("video_url", models.URLField(verbose_name="Video URL")),
                (
                    "video_id",
                    models.CharField(
                        blank=True,
                        help_text="YouTube video ID veya Instagram post ID",
                        max_length=100,
                        verbose_name="Video ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Başlık"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="tours.tour",
                        verbose_name="Tur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tur Videosu",
                "verbose_name_plural": "Tur Videoları",
                "ordering": ["tour", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="TourReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Müşteri Adı"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Puan",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Yorum")),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Onaylandı mı?"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review",
                        to="tours.tourreservation",
                        verbose_name="Rezervasyon",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="tours.tour",
                        verbose_name="Tur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tur Değerlendirmesi",
                "verbose_name_plural": "Tur Değerlendirmeleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "day_number",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Gün Numarası",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Örn: 1. Gün: İstanbul - İzmir",
                        max_length=200,
                        verbose_name="Gün Başlığı",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="O günün detaylı programı",
                        verbose_name="Gün Programı",
                    ),
                ),
                (
                    "activities",
                    models.TextField(
                        blank=True,
                        help_text="Yapılacak aktiviteler",
                        verbose_name="Aktiviteler",
                    ),
                ),
                (
                    "meals",
                    models.CharField(
                        blank=True,
                        help_text="Örn: Kahvaltı, Öğle Yemeği",
                        max_length=200,
                        verbose_name="Yemekler",
                    ),
                ),
                (
                    "accommodation",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Konaklama"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="tours.tour",
                        verbose_name="Tur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tur Programı",
                "verbose_name_plural": "Tur Programları",
                "ordering": ["tour", "day_number"],
            },
        ),
        migrations.CreateModel(
            name="TourPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Tutar"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Nakit"),
                            ("bank_transfer", "Banka Havalesi"),
                            ("credit_card", "Kredi Kartı"),
                            ("pos", "Sanal Pos"),
                            ("other", "Diğer"),
                        ],
                        max_length=50,
                        verbose_name="Ödeme Yöntemi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Başarısız"),
                            ("refunded", "İade Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ödeme Tarihi"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="İşlem ID"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="tours.tourreservation",
                        verbose_name="Rezervasyon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tur Ödemesi",
                "verbose_name_plural": "Tur Ödemeleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="tours/gallery/", verbose_name="Resim"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Başlık"),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alt Metin"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="tours.tour",
                        verbose_name="Tur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tur Resmi",
                "verbose_name_plural": "Tur Resimleri",
                "ordering": ["tour", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="TourGuest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ad")),
                ("last_name", models.CharField(max_length=100, verbose_name="Soyad")),
                (
                    "is_adult",
                    models.BooleanField(default=True, verbose_name="Yetişkin mi?"),
                ),
                ("age", models.IntegerField(blank=True, null=True, verbose_name="Yaş")),
                (
                    "tc_no",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="TC Kimlik No"
                    ),
                ),
                (
                    "passport_no",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Pasaport No"
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="tours.tourreservation",
                        verbose_name="Rezervasyon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tur Misafiri",
                "verbose_name_plural": "Tur Misafirleri",
                "ordering": ["reservation", "is_adult", "first_name"],
            },
        ),
        migrations.AddField(
            model_name="tour",
            name="city",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tours",
                to="tours.tourcity",
                verbose_name="Tur Şehri",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tours",
                to="tours.tourlocation",
                verbose_name="Tur Lokasyonu",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tours",
                to="tours.tourregion",
                verbose_name="Tur Bölgesi",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="tour_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tours",
                to="tours.tourtype",
                verbose_name="Tur Türü",
            ),
        ),
        migrations.CreateModel(
            name="TourRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Rota sırası",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Sıra",
                    ),
                ),
                (
                    "is_departure",
                    models.BooleanField(
                        default=False, verbose_name="Kalkış Noktası mı?"
                    ),
                ),
                (
                    "is_destination",
                    models.BooleanField(
                        default=False, verbose_name="Varış Noktası mı?"
                    ),
                ),
                (
                    "stay_duration",
                    models.CharField(
                        blank=True,
                        help_text="Örn: 2 gün, 1 gece",
                        max_length=50,
                        verbose_name="Kalış Süresi",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_routes",
                        to="tours.tourcity",
                        verbose_name="Şehir",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="tours.tour",
                        verbose_name="Tur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tur Rotası",
                "verbose_name_plural": "Tur Rotaları",
                "ordering": ["tour", "order"],
                "unique_together": {("tour", "order")},
            },
        ),
        migrations.CreateModel(
            name="TourReservationExtraService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Adet",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Birim Fiyat"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Toplam Fiyat"
                    ),
                ),
                (
                    "extra_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="tours.tourextraservice",
                        verbose_name="Ekstra Hizmet",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_extra_services",
                        to="tours.tourreservation",
                        verbose_name="Rezervasyon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezervasyon Ekstra Hizmeti",
                "verbose_name_plural": "Rezervasyon Ekstra Hizmetleri",
                "unique_together": {("reservation", "extra_service")},
            },
        ),
        migrations.AddIndex(
            model_name="tourreservation",
            index=models.Index(
                fields=["reservation_code"], name="tours_tourr_reserva_49f13f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tourreservation",
            index=models.Index(
                fields=["status", "payment_status"],
                name="tours_tourr_status_d20c42_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tourprogram",
            unique_together={("tour", "day_number")},
        ),
        migrations.AlterUniqueTogether(
            name="tourdate",
            unique_together={("tour", "date")},
        ),
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(
                fields=["status", "is_active"], name="tours_tour_status_b142f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tour",
            index=models.Index(
                fields=["region", "location", "tour_type"],
                name="tours_tour_region__5a0c81_idx",
            ),
        ),
    ]
