# Generated by Django 4.2.11 on 2025-11-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourpayment",
            name="payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="Ödeme Tarihi"),
        ),
        migrations.AlterField(
            model_name="tourpayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Nakit"),
                    ("bank_transfer", "Banka Havalesi"),
                    ("credit_card", "Kredi Kartı"),
                    ("iyzico", "İyzico"),
                    ("paytr", "PayTR"),
                    ("nestpay", "NestPay"),
                    ("garanti", "Garanti Sanal Pos"),
                    ("akbank", "Akbank Sanal Pos"),
                    ("other", "Diğer"),
                ],
                max_length=50,
                verbose_name="Ödeme Yöntemi",
            ),
        ),
        migrations.AlterField(
            model_name="tourpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Beklemede"),
                    ("completed", "Tamamlandı"),
                    ("failed", "Başarısız"),
                    ("refunded", "İade Edildi"),
                    ("cancelled", "İptal Edildi"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
    ]
