# Generated by Django 4.2.11 on 2025-11-09 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0002_alter_tourpayment_payment_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="demand_capacity_threshold",
            field=models.IntegerField(
                default=80,
                help_text="Bu yüzde dolduğunda fiyat otomatik artış yapsın",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Talep Kapasite Eşiği (%)",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="demand_price_increase",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=15.0,
                max_digits=5,
                null=True,
                verbose_name="Talep Fiyat Artışı (%)",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="early_booking_30_days_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=5.0,
                max_digits=5,
                null=True,
                verbose_name="30 Gün Öncesi İndirim (%)",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="early_booking_60_days_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=10.0,
                max_digits=5,
                null=True,
                verbose_name="60 Gün Öncesi İndirim (%)",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="early_booking_90_days_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=15.0,
                max_digits=5,
                null=True,
                verbose_name="90 Gün Öncesi İndirim (%)",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="enable_demand_pricing",
            field=models.BooleanField(
                default=False, verbose_name="Talep Bazlı Fiyat Artışı Aktif"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="enable_dynamic_pricing",
            field=models.BooleanField(
                default=False,
                help_text="Sezon, erken rezervasyon, son dakika fırsatları aktif olsun mu?",
                verbose_name="Dinamik Fiyatlandırma Aktif",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="enable_early_booking",
            field=models.BooleanField(
                default=False, verbose_name="Erken Rezervasyon İndirimi Aktif"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="enable_holiday_pricing",
            field=models.BooleanField(
                default=False, verbose_name="Bayram Tatili Fiyatlandırması Aktif"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="enable_last_minute",
            field=models.BooleanField(
                default=False, verbose_name="Son Dakika Fırsatları Aktif"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="enable_weekend_pricing",
            field=models.BooleanField(
                default=False, verbose_name="Hafta Sonu Fiyat Farkı Aktif"
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="high_season_end_month",
            field=models.IntegerField(
                blank=True,
                default=8,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Yüksek Sezon Bitiş Ayı",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="high_season_price_increase",
            field=models.DecimalField(
                decimal_places=2,
                default=25.0,
                help_text="Yüzde olarak (örn: 25 = %25 artış)",
                max_digits=5,
                verbose_name="Yüksek Sezon Fiyat Artışı (%)",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="high_season_start_month",
            field=models.IntegerField(
                blank=True,
                default=6,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Yüksek Sezon Başlangıç Ayı",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="holiday_price_increase",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=30.0,
                max_digits=5,
                null=True,
                verbose_name="Bayram Fiyat Artışı (%)",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="last_minute_3_days_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=30.0,
                max_digits=5,
                null=True,
                verbose_name="3 Gün İçinde İndirim (%)",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="last_minute_7_days_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=20.0,
                max_digits=5,
                null=True,
                verbose_name="7 Gün İçinde İndirim (%)",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="last_minute_auto_activate",
            field=models.BooleanField(
                default=False,
                help_text="Kontenjan %80 dolduğunda otomatik aktif olsun",
                verbose_name="Otomatik Aktifleşme",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="last_minute_capacity_threshold",
            field=models.IntegerField(
                default=80,
                help_text="Bu yüzde dolduğunda son dakika fırsatları aktif olsun",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Kapasite Eşiği (%)",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="low_season_end_month",
            field=models.IntegerField(
                blank=True,
                default=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Düşük Sezon Bitiş Ayı",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="low_season_price_decrease",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Yüzde olarak (örn: 20 = %20 indirim)",
                max_digits=5,
                verbose_name="Düşük Sezon Fiyat İndirimi (%)",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="low_season_start_month",
            field=models.IntegerField(
                blank=True,
                default=11,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
                verbose_name="Düşük Sezon Başlangıç Ayı",
            ),
        ),
        migrations.AddField(
            model_name="tour",
            name="weekend_price_increase",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=10.0,
                max_digits=5,
                null=True,
                verbose_name="Hafta Sonu Fiyat Artışı (%)",
            ),
        ),
    ]
