# Generated by Django 4.2.11 on 2025-11-09 19:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0003_tour_demand_capacity_threshold_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourWaitingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="Müşteri Adı"),
                ),
                (
                    "customer_surname",
                    models.CharField(max_length=100, verbose_name="Müşteri Soyadı"),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="E-posta"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=20, verbose_name="Telefon"),
                ),
                (
                    "customer_tc",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="TC Kimlik No"
                    ),
                ),
                (
                    "adult_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Yetişkin Sayısı",
                    ),
                ),
                (
                    "child_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Çocuk Sayısı",
                    ),
                ),
                (
                    "total_people",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Toplam Kişi",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Düşük sayı = Yüksek öncelik (VIP müşteriler için)",
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Beklemede"),
                            ("notified", "Bildirildi"),
                            ("converted", "Rezervasyona Dönüştürüldü"),
                            ("cancelled", "İptal Edildi"),
                            ("expired", "Süresi Doldu"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bildirim Tarihi"
                    ),
                ),
                (
                    "notification_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "E-posta"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=20,
                        verbose_name="Bildirim Yöntemi",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiting_lists",
                        to="tours.tour",
                        verbose_name="Tur",
                    ),
                ),
                (
                    "tour_date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiting_lists",
                        to="tours.tourdate",
                        verbose_name="Tur Tarihi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bekleme Listesi",
                "verbose_name_plural": "Bekleme Listeleri",
                "ordering": ["priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["tour", "tour_date", "status"],
                        name="tours_tourw_tour_id_fcab16_idx",
                    ),
                    models.Index(
                        fields=["status", "priority"],
                        name="tours_tourw_status_353234_idx",
                    ),
                ],
            },
        ),
    ]
