# Generated by Django 4.2.11 on 2025-11-09 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0005_tourcustomer_tourloyaltyhistory_tourcustomernote_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourAgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Acente Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Acente Kodu")),
                (
                    "contact_person",
                    models.CharField(max_length=100, verbose_name="İletişim Kişisi"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-posta")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                ("address", models.TextField(blank=True, verbose_name="Adres")),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Vergi No"
                    ),
                ),
                (
                    "tax_office",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Vergi Dairesi"
                    ),
                ),
                (
                    "commission_type",
                    models.CharField(
                        choices=[("percentage", "Yüzde"), ("fixed", "Sabit Tutar")],
                        default="percentage",
                        max_length=20,
                        verbose_name="Komisyon Tipi",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Yüzde ise %10 = 10.00, Sabit tutar ise TL cinsinden",
                        max_digits=5,
                        verbose_name="Komisyon Oranı",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
            ],
            options={
                "verbose_name": "Tur Acentesi",
                "verbose_name_plural": "Tur Acenteleri",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="tourreservation",
            name="customer_email",
            field=models.EmailField(
                db_index=True, max_length=254, verbose_name="E-posta"
            ),
        ),
        migrations.AlterField(
            model_name="tourwaitinglist",
            name="customer_email",
            field=models.EmailField(
                db_index=True, max_length=254, verbose_name="E-posta"
            ),
        ),
        migrations.CreateModel(
            name="TourReservationCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Komisyon hesaplanan tutar",
                        max_digits=10,
                        verbose_name="Temel Tutar",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Komisyon Oranı"
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Komisyon Tutarı"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("paid", "Ödendi"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Ödeme Durumu",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ödeme Tarihi"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissions",
                        to="tours.touragency",
                        verbose_name="Acente",
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission",
                        to="tours.tourreservation",
                        verbose_name="Rezervasyon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezervasyon Komisyonu",
                "verbose_name_plural": "Rezervasyon Komisyonları",
                "ordering": ["-created_at"],
            },
        ),
    ]
