# Generated by Django 4.2.11 on 2025-11-09 20:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0006_touragency_alter_tourreservation_customer_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Rehber Adı")),
                (
                    "surname",
                    models.CharField(max_length=100, verbose_name="Rehber Soyadı"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-posta"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Rehber Belge No"
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Örn: ["Türkçe", "İngilizce", "Almanca"]',
                        verbose_name="Bildiği Diller",
                    ),
                ),
                (
                    "specialties",
                    models.TextField(
                        blank=True,
                        help_text="Örn: Kültür turları, Doğa turları",
                        verbose_name="Uzmanlık Alanları",
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Saatlik Ücret",
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Günlük Ücret",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
            ],
            options={
                "verbose_name": "Tur Rehberi",
                "verbose_name_plural": "Tur Rehberleri",
                "ordering": ["name", "surname"],
            },
        ),
        migrations.CreateModel(
            name="TourHotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Otel Adı")),
                ("address", models.TextField(blank=True, verbose_name="Adres")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-posta"
                    ),
                ),
                (
                    "star_rating",
                    models.IntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Yıldız",
                    ),
                ),
                (
                    "room_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Örn: [{"type": "Standart", "capacity": 2}, {"type": "Suit", "capacity": 4}]',
                        verbose_name="Oda Tipleri",
                    ),
                ),
                (
                    "daily_rate_per_person",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Kişi Başı Günlük Ücret",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hotels",
                        to="tours.tourcity",
                        verbose_name="Şehir",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tur Oteli",
                "verbose_name_plural": "Tur Otelleri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TourTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Transfer Adı")),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("airport", "Havalimanı"),
                            ("hotel", "Otel"),
                            ("station", "İstasyon"),
                            ("other", "Diğer"),
                        ],
                        max_length=50,
                        verbose_name="Transfer Tipi",
                    ),
                ),
                (
                    "from_location",
                    models.CharField(max_length=200, verbose_name="Nereden"),
                ),
                (
                    "to_location",
                    models.CharField(max_length=200, verbose_name="Nereye"),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Mesafe (KM)",
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Süre (Dakika)",
                    ),
                ),
                (
                    "price_per_person",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Kişi Başı Fiyat",
                    ),
                ),
                (
                    "price_per_vehicle",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Araç Başı Fiyat",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
            ],
            options={
                "verbose_name": "Transfer Hizmeti",
                "verbose_name_plural": "Transfer Hizmetleri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TourVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(max_length=20, unique=True, verbose_name="Plaka"),
                ),
                ("brand", models.CharField(max_length=50, verbose_name="Marka")),
                ("model", models.CharField(max_length=50, verbose_name="Model")),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Yıl",
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Kapasite",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("bus", "Otobüs"),
                            ("minibus", "Minibüs"),
                            ("van", "Van"),
                            ("car", "Araba"),
                        ],
                        max_length=50,
                        verbose_name="Araç Tipi",
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Şoför Adı"
                    ),
                ),
                (
                    "driver_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Şoför Telefonu"
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Günlük Ücret",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
            ],
            options={
                "verbose_name": "Tur Aracı",
                "verbose_name_plural": "Tur Araçları",
                "ordering": ["plate_number"],
            },
        ),
        migrations.AddField(
            model_name="tourreservation",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="tours.touragency",
                verbose_name="Acente",
            ),
        ),
        migrations.CreateModel(
            name="TourReservationOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "guide_days",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Rehber Gün Sayısı",
                    ),
                ),
                (
                    "guide_total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Rehber Toplam Maliyet",
                    ),
                ),
                (
                    "vehicle_days",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Araç Gün Sayısı",
                    ),
                ),
                (
                    "vehicle_total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Araç Toplam Maliyet",
                    ),
                ),
                (
                    "hotel_nights",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Otel Gece Sayısı",
                    ),
                ),
                (
                    "hotel_total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Otel Toplam Maliyet",
                    ),
                ),
                (
                    "transfer_total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Transfer Toplam Maliyet",
                    ),
                ),
                (
                    "total_operation_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Toplam Operasyonel Maliyet",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Operasyonel Notlar"),
                ),
                (
                    "guide",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="tours.tourguide",
                        verbose_name="Rehber",
                    ),
                ),
                (
                    "hotels",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reservations",
                        to="tours.tourhotel",
                        verbose_name="Oteller",
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation",
                        to="tours.tourreservation",
                        verbose_name="Rezervasyon",
                    ),
                ),
                (
                    "transfers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="reservations",
                        to="tours.tourtransfer",
                        verbose_name="Transferler",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="tours.tourvehicle",
                        verbose_name="Araç",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezervasyon Operasyonu",
                "verbose_name_plural": "Rezervasyon Operasyonları",
            },
        ),
    ]
