# Generated by Django 4.2.11 on 2025-11-09 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tours", "0007_tourguide_tourhotel_tourtransfer_tourvehicle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Kampanya Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Kampanya Kodu")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("discount_percentage", "Yüzde İndirim"),
                            ("discount_fixed", "Sabit Tutar İndirim"),
                            ("buy_one_get_one", "Al 1 Bedava 1"),
                            ("early_booking", "Erken Rezervasyon"),
                            ("group_discount", "Grup İndirimi"),
                            ("loyalty_bonus", "Sadakat Bonusu"),
                        ],
                        max_length=30,
                        verbose_name="Kampanya Tipi",
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="İndirim Yüzdesi",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="İndirim Tutarı",
                    ),
                ),
                (
                    "min_purchase_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Minimum Alış Tutarı",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Maksimum İndirim Tutarı",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "usage_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Toplam kaç kez kullanılabileceği (boş = sınırsız)",
                        null=True,
                        verbose_name="Kullanım Limiti",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="Kullanım Sayısı"),
                ),
                (
                    "per_customer_limit",
                    models.IntegerField(
                        default=1,
                        help_text="Bir müşteri kaç kez kullanabilir",
                        verbose_name="Müşteri Başı Limit",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Öne Çıkan mı?"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="campaigns/",
                        verbose_name="Kampanya Görseli",
                    ),
                ),
                (
                    "applicable_tour_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="campaigns",
                        to="tours.tourtype",
                        verbose_name="Uygulanabilir Tur Türleri",
                    ),
                ),
                (
                    "applicable_tours",
                    models.ManyToManyField(
                        blank=True,
                        related_name="campaigns",
                        to="tours.tour",
                        verbose_name="Uygulanabilir Turlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tur Kampanyası",
                "verbose_name_plural": "Tur Kampanyaları",
                "ordering": ["-is_featured", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TourNotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Şablon Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Şablon Kodu")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email", "E-posta"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=20,
                        verbose_name="Bildirim Tipi",
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("reservation_created", "Rezervasyon Oluşturuldu"),
                            ("reservation_confirmed", "Rezervasyon Onaylandı"),
                            ("reservation_cancelled", "Rezervasyon İptal Edildi"),
                            ("payment_received", "Ödeme Alındı"),
                            ("tour_reminder", "Tur Hatırlatması"),
                            ("waiting_list_available", "Bekleme Listesi Müsait"),
                            ("voucher_ready", "Voucher Hazır"),
                        ],
                        max_length=50,
                        verbose_name="Tetikleyici Olay",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="E-posta için",
                        max_length=200,
                        verbose_name="Konu",
                    ),
                ),
                ("message", models.TextField(verbose_name="Mesaj İçeriği")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="Kullanılabilir Değişkenler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim Şablonu",
                "verbose_name_plural": "Bildirim Şablonları",
                "ordering": ["notification_type", "trigger_event"],
            },
        ),
        migrations.AddField(
            model_name="tourreservation",
            name="promo_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, verbose_name="Promosyon Kodu"
            ),
        ),
        migrations.CreateModel(
            name="TourPromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Promosyon Kodu",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "usage_limit",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Kullanım Limiti"
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="Kullanım Sayısı"),
                ),
                (
                    "per_customer_limit",
                    models.IntegerField(default=1, verbose_name="Müşteri Başı Limit"),
                ),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateField(verbose_name="Bitiş Tarihi")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_codes",
                        to="tours.tourcampaign",
                        verbose_name="Kampanya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promosyon Kodu",
                "verbose_name_plural": "Promosyon Kodları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="tourreservation",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="tours.tourcampaign",
                verbose_name="Kampanya",
            ),
        ),
        migrations.CreateModel(
            name="TourNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("email", "E-posta"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=20,
                        verbose_name="Bildirim Tipi",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Alıcı E-posta"
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Alıcı Telefon"
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=200, verbose_name="Konu"),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("sent", "Gönderildi"),
                            ("failed", "Başarısız"),
                            ("delivered", "Teslim Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gönderilme Tarihi"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="tours.tourcustomer",
                        verbose_name="Müşteri",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="tours.tourreservation",
                        verbose_name="Rezervasyon",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="tours.tournotificationtemplate",
                        verbose_name="Şablon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim",
                "verbose_name_plural": "Bildirimler",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "notification_type"],
                        name="tours_tourn_status_1507b1_idx",
                    ),
                    models.Index(
                        fields=["reservation", "status"],
                        name="tours_tourn_reserva_c20fd6_idx",
                    ),
                ],
            },
        ),
    ]
