# Generated by Django 4.2.11 on 2025-11-12 02:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_core', '0003_customer_customernote_customerloyaltyhistory_and_more'),
        ('hotels', '0004_hotelextraservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        # ('reception', '0003_reservation_total_paid'),  # KALDIRILDI - Reception modülü yeniden inşa edilecek
    ]

    operations = [
        migrations.CreateModel(
            name='RoomQualityInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('inspection_type', models.CharField(choices=[('pre_checkin', 'Check-In Öncesi'), ('post_checkout', 'Check-Out Sonrası'), ('routine', 'Rutin Kontrol'), ('complaint', 'Şikayet Sonrası'), ('random', 'Rastgele')], db_index=True, default='routine', max_length=50, verbose_name='Kontrol Tipi')),
                ('inspected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kontrol Tarihi')),
                ('overall_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Genel Puan')),
                ('cleanliness_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Temizlik Puanı')),
                ('maintenance_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Bakım Puanı')),
                ('amenities_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Olanaklar Puanı')),
                ('status', models.CharField(choices=[('passed', 'Geçti'), ('failed', 'Başarısız'), ('needs_improvement', 'İyileştirme Gerekli')], db_index=True, default='passed', max_length=20, verbose_name='Durum')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('action_required', models.BooleanField(default=False, verbose_name='Aksiyon Gerekli mi?')),
                ('action_taken', models.TextField(blank=True, verbose_name='Alınan Aksiyon')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspections', to='hotels.hotel', verbose_name='Otel')),
                ('inspected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_quality_inspections', to=settings.AUTH_USER_MODEL, verbose_name='Kontrol Eden')),
                # ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_inspections', to='reception.reservation', verbose_name='Rezervasyon')),  # KALDIRILDI
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_inspections', to='hotels.roomnumber', verbose_name='Oda Numarası')),
            ],
            options={
                'verbose_name': 'Oda Kalite Kontrolü',
                'verbose_name_plural': 'Oda Kalite Kontrolleri',
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('name', models.CharField(max_length=200, verbose_name='Standart Adı')),
                ('category', models.CharField(choices=[('cleanliness', 'Temizlik'), ('maintenance', 'Bakım'), ('service', 'Hizmet'), ('safety', 'Güvenlik'), ('comfort', 'Konfor'), ('other', 'Diğer')], default='cleanliness', max_length=50, verbose_name='Kategori')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('minimum_score', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Minimum Puan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_standards', to='hotels.hotel', verbose_name='Otel')),
            ],
            options={
                'verbose_name': 'Kalite Standardı',
                'verbose_name_plural': 'Kalite Standartları',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QualityControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('require_pre_checkin_inspection', models.BooleanField(default=True, verbose_name='Check-In Öncesi Kontrol Zorunlu mu?')),
                ('require_post_checkout_inspection', models.BooleanField(default=True, verbose_name='Check-Out Sonrası Kontrol Zorunlu mu?')),
                ('routine_inspection_frequency', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Rutin Kontrol Sıklığı (Gün)')),
                ('minimum_overall_score', models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Minimum Genel Puan')),
                ('auto_escalate_low_scores', models.BooleanField(default=True, verbose_name='Düşük Puanları Otomatik Üst Seviyeye Taşı')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_control_settings', to='hotels.hotel', verbose_name='Otel')),
            ],
            options={
                'verbose_name': 'Kalite Kontrol Ayarları',
                'verbose_name_plural': 'Kalite Kontrol Ayarları',
            },
        ),
        migrations.CreateModel(
            name='QualityChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('item_name', models.CharField(max_length=200, verbose_name='Öğe Adı')),
                ('category', models.CharField(choices=[('cleanliness', 'Temizlik'), ('maintenance', 'Bakım'), ('amenities', 'Olanaklar'), ('safety', 'Güvenlik'), ('comfort', 'Konfor'), ('other', 'Diğer')], default='cleanliness', max_length=50, verbose_name='Kategori')),
                ('is_checked', models.BooleanField(default=False, verbose_name='Kontrol Edildi mi?')),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Puan')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='quality_control.roomqualityinspection', verbose_name='Kontrol')),
            ],
            options={
                'verbose_name': 'Kontrol Listesi Öğesi',
                'verbose_name_plural': 'Kontrol Listesi Öğeleri',
                'ordering': ['category', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='QualityAuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('report_date', models.DateField(db_index=True, verbose_name='Rapor Tarihi')),
                ('total_inspections', models.IntegerField(default=0, verbose_name='Toplam Kontrol')),
                ('passed_inspections', models.IntegerField(default=0, verbose_name='Geçen Kontroller')),
                ('failed_inspections', models.IntegerField(default=0, verbose_name='Başarısız Kontroller')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ortalama Puan')),
                ('average_cleanliness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ortalama Temizlik Puanı')),
                ('average_maintenance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ortalama Bakım Puanı')),
                ('total_complaints', models.IntegerField(default=0, verbose_name='Toplam Şikayet')),
                ('resolved_complaints', models.IntegerField(default=0, verbose_name='Çözülen Şikayet')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quality_reports', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_audit_reports', to='hotels.hotel', verbose_name='Otel')),
            ],
            options={
                'verbose_name': 'Denetim Raporu',
                'verbose_name_plural': 'Denetim Raporları',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('complaint_type', models.CharField(choices=[('room_quality', 'Oda Kalitesi'), ('service', 'Hizmet'), ('cleanliness', 'Temizlik'), ('noise', 'Gürültü'), ('staff', 'Personel'), ('facilities', 'Tesisler'), ('other', 'Diğer')], db_index=True, default='other', max_length=50, verbose_name='Şikayet Tipi')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], db_index=True, default='normal', max_length=20, verbose_name='Öncelik')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Bildirim Tarihi')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('investigating', 'İnceleniyor'), ('resolved', 'Çözüldü'), ('closed', 'Kapatıldı'), ('escalated', 'Üst Seviyeye Taşındı')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Çözüm Tarihi')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Çözüm Notları')),
                ('customer_satisfaction', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Müşteri Memnuniyeti')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='tenant_core.customer', verbose_name='Müşteri')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_complaints', to='hotels.hotel', verbose_name='Otel')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Bildiren')),
                # ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='reception.reservation', verbose_name='Rezervasyon')),  # KALDIRILDI
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Çözen')),
            ],
            options={
                'verbose_name': 'Müşteri Şikayeti',
                'verbose_name_plural': 'Müşteri Şikayetleri',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.AddIndex(
            model_name='roomqualityinspection',
            index=models.Index(fields=['hotel', 'status', 'inspected_at'], name='quality_con_hotel_i_982ae4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qualityauditreport',
            unique_together={('hotel', 'report_date')},
        ),
        migrations.AddIndex(
            model_name='customercomplaint',
            index=models.Index(fields=['hotel', 'status', 'priority'], name='quality_con_hotel_i_d98a09_idx'),
        ),
    ]
