# Generated by Django 4.2.11 on 2025-11-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Sağlayıcı Adı"),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI (ChatGPT)"),
                            ("anthropic", "Anthropic (Claude)"),
                            ("google", "Google (Gemini)"),
                            ("cursor", "Cursor"),
                            ("other", "Diğer"),
                        ],
                        max_length=50,
                        verbose_name="Sağlayıcı Tipi",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "icon",
                    models.CharField(
                        default="🤖",
                        help_text="Emoji veya Font Awesome class",
                        max_length=50,
                        verbose_name="İkon",
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        blank=True,
                        help_text="API endpoint URL",
                        verbose_name="API Base URL",
                    ),
                ),
                (
                    "api_key_encrypted",
                    models.TextField(
                        blank=True,
                        help_text="Ana API key şifreli olarak saklanır",
                        verbose_name="API Key (Şifreli)",
                    ),
                ),
                (
                    "api_key_label",
                    models.CharField(
                        default="API Key",
                        help_text="Formda gösterilecek etiket",
                        max_length=100,
                        verbose_name="API Key Etiketi",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Ek ayarlar (timeout, retry vb.)",
                        verbose_name="Ayarlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Sağlayıcı",
                "verbose_name_plural": "AI Sağlayıcıları",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Model Adı")),
                ("code", models.SlugField(verbose_name="Kod")),
                (
                    "model_id",
                    models.CharField(
                        help_text="API'de kullanılan model ID (örn: gpt-4, claude-3-opus)",
                        max_length=100,
                        verbose_name="Model ID",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "credit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Bu modeli kullanmak için düşülecek kredi miktarı",
                        max_digits=10,
                        verbose_name="Kredi Maliyeti",
                    ),
                ),
                (
                    "max_tokens",
                    models.IntegerField(
                        blank=True,
                        help_text="Maksimum token sayısı",
                        null=True,
                        verbose_name="Maksimum Token",
                    ),
                ),
                (
                    "supports_streaming",
                    models.BooleanField(default=True, verbose_name="Streaming Desteği"),
                ),
                (
                    "supports_function_calling",
                    models.BooleanField(
                        default=False, verbose_name="Function Calling Desteği"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Bu sağlayıcı için varsayılan model",
                        verbose_name="Varsayılan Model mi?",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Model özel ayarları",
                        verbose_name="Ayarlar",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="ai_shared.aiprovider",
                        verbose_name="Sağlayıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Model",
                "verbose_name_plural": "AI Modelleri",
                "ordering": ["provider", "sort_order", "name"],
                "unique_together": {("provider", "code")},
            },
        ),
        migrations.CreateModel(
            name="PackageAI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "monthly_credit_limit",
                    models.IntegerField(
                        default=1000,
                        help_text="Paket ile birlikte verilen aylık kredi miktarı (-1 = sınırsız)",
                        verbose_name="Aylık Kredi Limiti",
                    ),
                ),
                (
                    "credit_renewal_type",
                    models.CharField(
                        choices=[("monthly", "Aylık"), ("yearly", "Yıllık")],
                        default="monthly",
                        max_length=20,
                        verbose_name="Kredi Yenileme Tipi",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "ai_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_configs",
                        to="ai_shared.aimodel",
                        verbose_name="AI Model",
                    ),
                ),
                (
                    "ai_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_configs",
                        to="ai_shared.aiprovider",
                        verbose_name="AI Sağlayıcı",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_configs",
                        to="packages.package",
                        verbose_name="Paket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paket AI Yapılandırması",
                "verbose_name_plural": "Paket AI Yapılandırmaları",
                "ordering": ["package", "ai_provider", "ai_model"],
                "unique_together": {("package", "ai_provider", "ai_model")},
            },
        ),
    ]
