# Generated by Django 4.2.11 on 2025-11-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Modül Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Modül Kodu")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "icon",
                    models.CharField(
                        default="📦",
                        help_text="Emoji veya Font Awesome class",
                        max_length=50,
                        verbose_name="İkon",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("reservation", "Rezervasyon"),
                            ("housekeeping", "Housekeeping"),
                            ("channel", "Kanal Entegrasyonu"),
                            ("payment", "Ödeme"),
                            ("reporting", "Raporlama"),
                            ("other", "Diğer"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        blank=True,
                        help_text="apps.tenant_apps.reservations",
                        max_length=100,
                        verbose_name="Django App Adı",
                    ),
                ),
                (
                    "url_prefix",
                    models.CharField(
                        blank=True,
                        help_text="/reservations/",
                        max_length=50,
                        verbose_name="URL Prefix",
                    ),
                ),
                (
                    "available_permissions",
                    models.JSONField(default=dict, verbose_name="Mevcut İzinler"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_core",
                    models.BooleanField(
                        default=False,
                        help_text="Temel modüller tüm paketlerde zorunludur",
                        verbose_name="Temel Modül mü?",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Ayarlar"),
                ),
            ],
            options={
                "verbose_name": "Modül",
                "verbose_name_plural": "Modüller",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
