# Generated by Django 4.2.11 on 2025-11-13 22:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('name', models.CharField(max_length=200, verbose_name='Kanal Adı')),
                ('code', models.SlugField(unique=True, verbose_name='Kanal Kodu')),
                ('channel_type', models.CharField(choices=[('ota', 'OTA (Online Travel Agency)'), ('gds', 'GDS (Global Distribution System)'), ('metasearch', 'Meta Arama Motoru'), ('direct', 'Direkt Rezervasyon'), ('other', 'Diğer')], default='ota', max_length=20, verbose_name='Kanal Tipi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('api_type', models.CharField(default='xml', help_text='xml, json, soap, rest vb.', max_length=50, verbose_name='API Tipi')),
                ('api_documentation_url', models.URLField(blank=True, verbose_name='API Dokümantasyon URL')),
                ('api_endpoint_template', models.CharField(blank=True, help_text='Örn: https://api.booking.com/v1/{endpoint}', max_length=500, verbose_name='API Endpoint Şablonu')),
                ('required_fields', models.JSONField(default=dict, help_text='{"api_key": "API Key", "api_secret": "API Secret"}', verbose_name='Gerekli Alanlar')),
                ('optional_fields', models.JSONField(default=dict, help_text='{"hotel_id": "Otel ID", "username": "Kullanıcı Adı"}', verbose_name='Opsiyonel Alanlar')),
                ('supports_pricing', models.BooleanField(default=True, verbose_name='Fiyat Aktarımı Desteği')),
                ('supports_availability', models.BooleanField(default=True, verbose_name='Müsaitlik Aktarımı Desteği')),
                ('supports_reservations', models.BooleanField(default=True, verbose_name='Rezervasyon Desteği')),
                ('supports_two_way', models.BooleanField(default=True, help_text='Hem push hem pull desteği', verbose_name='İki Yönlü Senkronizasyon')),
                ('supports_commission', models.BooleanField(default=True, verbose_name='Komisyon Yönetimi')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Varsayılan Komisyon Oranı (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Popüler mi?')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('icon', models.CharField(default='fas fa-globe', help_text='Font Awesome class', max_length=50, verbose_name='İkon')),
                ('logo_url', models.URLField(blank=True, verbose_name='Logo URL')),
            ],
            options={
                'verbose_name': 'Kanal Şablonu',
                'verbose_name_plural': 'Kanal Şablonları',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['code'], name='modules_cha_code_dec687_idx'), models.Index(fields=['channel_type'], name='modules_cha_channel_17cacf_idx'), models.Index(fields=['is_active'], name='modules_cha_is_acti_f52857_idx')],
            },
        ),
    ]
