# Generated by Django 4.2.11 on 2025-11-12 02:11

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0004_hotelextraservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('default_shift_duration', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Varsayılan Vardiya Süresi (Saat)')),
                ('overtime_threshold', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5, verbose_name='Mesai Eşiği (Saat)')),
                ('default_overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=5, verbose_name='Varsayılan Mesai Oranı')),
                ('annual_leave_days', models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Yıllık İzin Günü')),
                ('sick_leave_days', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hastalık İzni Günü')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_settings', to='hotels.hotel', verbose_name='Otel')),
            ],
            options={
                'verbose_name': 'Personel Yönetimi Ayarları',
                'verbose_name_plural': 'Personel Yönetimi Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('employee_id', models.CharField(db_index=True, max_length=50, verbose_name='Personel No')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('department', models.CharField(choices=[('reception', 'Resepsiyon'), ('housekeeping', 'Kat Hizmetleri'), ('maintenance', 'Teknik Servis'), ('kitchen', 'Mutfak'), ('restaurant', 'Restoran'), ('security', 'Güvenlik'), ('management', 'Yönetim'), ('sales', 'Satış'), ('other', 'Diğer')], db_index=True, default='other', max_length=100, verbose_name='Departman')),
                ('position', models.CharField(max_length=100, verbose_name='Pozisyon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Adres')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='İşe Başlama Tarihi')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='İşten Ayrılma Tarihi')),
                ('employment_type', models.CharField(choices=[('full_time', 'Tam Zamanlı'), ('part_time', 'Yarı Zamanlı'), ('contract', 'Sözleşmeli'), ('intern', 'Stajyer')], default='full_time', max_length=20, verbose_name='İstihdam Tipi')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Maaş')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='hotels.hotel', verbose_name='Otel')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personel',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('shift_date', models.DateField(db_index=True, verbose_name='Vardiya Tarihi')),
                ('shift_type', models.CharField(choices=[('morning', 'Sabah'), ('afternoon', 'Öğleden Sonra'), ('evening', 'Akşam'), ('night', 'Gece'), ('custom', 'Özel')], default='morning', max_length=20, verbose_name='Vardiya Tipi')),
                ('start_time', models.TimeField(verbose_name='Başlangıç Saati')),
                ('end_time', models.TimeField(verbose_name='Bitiş Saati')),
                ('status', models.CharField(choices=[('scheduled', 'Planlandı'), ('confirmed', 'Onaylandı'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('no_show', 'Gelmedi')], db_index=True, default='scheduled', max_length=20, verbose_name='Durum')),
                ('actual_start_time', models.TimeField(blank=True, null=True, verbose_name='Gerçek Başlangıç Saati')),
                ('actual_end_time', models.TimeField(blank=True, null=True, verbose_name='Gerçek Bitiş Saati')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='hotels.hotel', verbose_name='Otel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='staff.staff', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Vardiya',
                'verbose_name_plural': 'Vardiyalar',
                'ordering': ['-shift_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('salary_month', models.DateField(db_index=True, verbose_name='Maaş Ayı')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Temel Maaş')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Mesai Saati')),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=Decimal('1.5'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Mesai Oranı')),
                ('bonuses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Primler')),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Kesintiler')),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Brüt Maaş')),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Net Maaş')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('paid', models.BooleanField(default=False, verbose_name='Ödendi mi?')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='hotels.hotel', verbose_name='Otel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='staff.staff', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Maaş Kaydı',
                'verbose_name_plural': 'Maaş Kayıtları',
                'ordering': ['-salary_month'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('review_period_start', models.DateField(db_index=True, verbose_name='Değerlendirme Dönemi Başlangıç')),
                ('review_period_end', models.DateField(db_index=True, verbose_name='Değerlendirme Dönemi Bitiş')),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Değerlendirme Tarihi')),
                ('attendance_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Devam Puanı')),
                ('performance_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Performans Puanı')),
                ('teamwork_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Takım Çalışması Puanı')),
                ('communication_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='İletişim Puanı')),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Genel Puan')),
                ('strengths', models.TextField(blank=True, verbose_name='Güçlü Yönler')),
                ('areas_for_improvement', models.TextField(blank=True, verbose_name='Geliştirilmesi Gereken Alanlar')),
                ('goals', models.TextField(blank=True, verbose_name='Hedefler')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='hotels.hotel', verbose_name='Otel')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_performance_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Değerlendiren')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='staff.staff', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Performans Değerlendirmesi',
                'verbose_name_plural': 'Performans Değerlendirmeleri',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('leave_type', models.CharField(choices=[('annual', 'Yıllık İzin'), ('sick', 'Hastalık İzni'), ('personal', 'Özel İzin'), ('unpaid', 'Ücretsiz İzin'), ('maternity', 'Doğum İzni'), ('paternity', 'Babalık İzni'), ('other', 'Diğer')], default='annual', max_length=20, verbose_name='İzin Tipi')),
                ('start_date', models.DateField(db_index=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(db_index=True, verbose_name='Bitiş Tarihi')),
                ('total_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Toplam Gün')),
                ('reason', models.TextField(verbose_name='Sebep')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İnceleme Tarihi')),
                ('review_notes', models.TextField(blank=True, verbose_name='İnceleme Notları')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hotels.hotel', verbose_name='Otel')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='staff.staff', verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'İzin Talebi',
                'verbose_name_plural': 'İzin Talepleri',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['hotel', 'department', 'is_active'], name='staff_staff_hotel_i_7f39a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('hotel', 'employee_id')},
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['hotel', 'shift_date', 'status'], name='staff_shift_hotel_i_86a549_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['hotel', 'salary_month', 'paid'], name='staff_salar_hotel_i_8d0a44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('hotel', 'staff', 'salary_month')},
        ),
        migrations.AddIndex(
            model_name='performancereview',
            index=models.Index(fields=['hotel', 'staff', 'review_period_start'], name='staff_perfo_hotel_i_ac040e_idx'),
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['hotel', 'status', 'start_date'], name='staff_leave_hotel_i_78bdd2_idx'),
        ),
    ]
