# Generated by Django 4.2.11 on 2025-11-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("modules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Paket Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Paket Kodu")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Aylık Fiyat"
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Yıllık Fiyat",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Türk Lirası"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                        ],
                        default="TRY",
                        max_length=3,
                        verbose_name="Para Birimi",
                    ),
                ),
                (
                    "max_hotels",
                    models.IntegerField(default=1, verbose_name="Maksimum Otel Sayısı"),
                ),
                (
                    "max_rooms",
                    models.IntegerField(default=10, verbose_name="Maksimum Oda Sayısı"),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        default=3, verbose_name="Maksimum Kullanıcı Sayısı"
                    ),
                ),
                (
                    "max_reservations_per_month",
                    models.IntegerField(
                        default=100, verbose_name="Aylık Maksimum Rezervasyon"
                    ),
                ),
                (
                    "max_storage_gb",
                    models.IntegerField(
                        default=1, verbose_name="Maksimum Depolama (GB)"
                    ),
                ),
                (
                    "max_api_calls_per_day",
                    models.IntegerField(
                        default=1000, verbose_name="Günlük Maksimum API Çağrısı"
                    ),
                ),
                (
                    "trial_days",
                    models.IntegerField(default=14, verbose_name="Deneme Süresi (Gün)"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Öne Çıkan mı?"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ek Ayarlar"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paket",
                "verbose_name_plural": "Paketler",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PackageModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(default=dict, verbose_name="Yetkiler"),
                ),
                (
                    "limits",
                    models.JSONField(blank=True, default=dict, verbose_name="Limitler"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Zorunlu mu?"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_packages",
                        to="modules.module",
                        verbose_name="Modül",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_modules",
                        to="packages.package",
                        verbose_name="Paket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paket Modülü",
                "verbose_name_plural": "Paket Modülleri",
                "ordering": ["package", "module"],
                "unique_together": {("package", "module")},
            },
        ),
        migrations.AddField(
            model_name="package",
            name="modules",
            field=models.ManyToManyField(
                related_name="packages",
                through="packages.PackageModule",
                to="modules.module",
                verbose_name="Modüller",
            ),
        ),
    ]
