# Generated by Django 4.2.11 on 2025-11-09 19:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_core", "0001_initial"),
        ("tours", "0004_tourwaitinglist"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "customer_code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Müşteri Kodu",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ad")),
                ("last_name", models.CharField(max_length=100, verbose_name="Soyad")),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="E-posta",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                (
                    "tc_no",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="TC Kimlik No"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adres")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Şehir"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Türkiye", max_length=100, verbose_name="Ülke"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Posta Kodu"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Doğum Tarihi"
                    ),
                ),
                (
                    "special_dates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Örn: [{"date": "2024-12-25", "name": "Evlilik Yıldönümü"}]',
                        verbose_name="Özel Günler",
                    ),
                ),
                (
                    "loyalty_points",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Sadakat Puanı",
                    ),
                ),
                (
                    "total_reservations",
                    models.IntegerField(default=0, verbose_name="Toplam Rezervasyon"),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Toplam Harcama",
                    ),
                ),
                (
                    "vip_level",
                    models.CharField(
                        choices=[
                            ("regular", "Normal"),
                            ("silver", "Gümüş (5+ rezervasyon)"),
                            ("gold", "Altın (10+ rezervasyon)"),
                            ("platinum", "Platin (20+ rezervasyon)"),
                            ("diamond", "Elmas (50+ rezervasyon)"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="VIP Seviyesi",
                    ),
                ),
                (
                    "preferred_travel_months",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Örn: [6, 7, 8] (Haziran, Temmuz, Ağustos)",
                        verbose_name="Tercih Edilen Seyahat Ayları",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Müşteri hakkında özel notlar",
                        verbose_name="Notlar",
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(
                        blank=True,
                        help_text="Müşterinin özel istekleri",
                        verbose_name="Özel İstekler",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_vip",
                    models.BooleanField(default=False, verbose_name="VIP Müşteri mi?"),
                ),
                (
                    "last_reservation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son Rezervasyon Tarihi"
                    ),
                ),
                (
                    "preferred_regions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preferred_customers",
                        to="tours.tourregion",
                        verbose_name="Tercih Edilen Bölgeler",
                    ),
                ),
                (
                    "preferred_tour_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preferred_customers",
                        to="tours.tourtype",
                        verbose_name="Tercih Edilen Tur Türleri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tur Müşterisi",
                "verbose_name_plural": "Tur Müşterileri",
                "ordering": ["-total_spent", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourLoyaltyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Pozitif = Ekleme, Negatif = Kullanım",
                        verbose_name="Puan",
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="Sebep"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_history",
                        to="tours.tourcustomer",
                        verbose_name="Müşteri",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loyalty_points",
                        to="tours.tourreservation",
                        verbose_name="Rezervasyon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sadakat Puanı Geçmişi",
                "verbose_name_plural": "Sadakat Puanı Geçmişleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TourCustomerNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("note", models.TextField(verbose_name="Not")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="Önemli mi?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_notes",
                        to="tenant_core.tenantuser",
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_history",
                        to="tours.tourcustomer",
                        verbose_name="Müşteri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Müşteri Notu",
                "verbose_name_plural": "Müşteri Notları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="tourreservation",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="tours.tourcustomer",
                verbose_name="Müşteri Profili",
            ),
        ),
        migrations.AddIndex(
            model_name="tourcustomer",
            index=models.Index(fields=["email"], name="tours_tourc_email_ed9529_idx"),
        ),
        migrations.AddIndex(
            model_name="tourcustomer",
            index=models.Index(
                fields=["customer_code"], name="tours_tourc_custome_89cceb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tourcustomer",
            index=models.Index(
                fields=["vip_level", "is_active"], name="tours_tourc_vip_lev_0b07d2_idx"
            ),
        ),
    ]
