# Generated by Django 4.2.11 on 2025-11-10 14:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Hesap Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Hesap Kodu")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("cash", "Nakit Kasa"),
                            ("bank", "Banka Hesabı"),
                            ("credit_card", "Kredi Kartı"),
                            ("digital_wallet", "Dijital Cüzdan"),
                            ("check", "Çek"),
                            ("other", "Diğer"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Hesap Tipi",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Türk Lirası"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                        ],
                        default="TRY",
                        max_length=3,
                        verbose_name="Para Birimi",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Banka Adı"
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Şube Adı"
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Hesap No"
                    ),
                ),
                (
                    "iban",
                    models.CharField(blank=True, max_length=34, verbose_name="IBAN"),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Başlangıç Bakiyesi",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Otomatik hesaplanır",
                        max_digits=15,
                        verbose_name="Güncel Bakiye",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Varsayılan hesap olarak kullanılır",
                        verbose_name="Varsayılan Hesap mı?",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Ayarlar"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
            ],
            options={
                "verbose_name": "Kasa Hesabı",
                "verbose_name_plural": "Kasa Hesapları",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CashTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(
                        help_text="Otomatik oluşturulur",
                        max_length=50,
                        unique=True,
                        verbose_name="İşlem No",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("income", "Gelir"),
                            ("expense", "Gider"),
                            ("transfer", "Transfer"),
                            ("adjustment", "Düzeltme"),
                        ],
                        max_length=20,
                        verbose_name="İşlem Tipi",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tutar",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "source_module",
                    models.CharField(
                        blank=True,
                        help_text="tours, reservations, vb.",
                        max_length=50,
                        verbose_name="Kaynak Modül",
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Kaynak modülün kayıt ID'si",
                        null=True,
                        verbose_name="Kaynak ID",
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="Rezervasyon no, Tur adı vb.",
                        max_length=200,
                        verbose_name="Kaynak Referans",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Nakit"),
                            ("bank_transfer", "Banka Havalesi"),
                            ("credit_card", "Kredi Kartı"),
                            ("check", "Çek"),
                            ("digital_wallet", "Dijital Cüzdan"),
                            ("other", "Diğer"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Ödeme Yöntemi",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ödeme Tarihi"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Vadeli ödemeler için",
                        null=True,
                        verbose_name="Vade Tarihi",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "İptal Edildi"),
                            ("reversed", "Geri Alındı"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "is_reconciled",
                    models.BooleanField(
                        default=False, verbose_name="Mutabakat Yapıldı mı?"
                    ),
                ),
                (
                    "reconciled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Mutabakat Tarihi"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Onay Tarihi"
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Dosya URL'leri listesi",
                        verbose_name="Ekler",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ek Bilgiler"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finance.cashaccount",
                        verbose_name="Kasa Hesabı",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_cash_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Onaylayan",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_cash_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşlem Yapan",
                    ),
                ),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciled_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mutabakat Yapan",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transfer işlemleri için",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_transfers",
                        to="finance.cashaccount",
                        verbose_name="Hedef Hesap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kasa İşlemi",
                "verbose_name_plural": "Kasa İşlemleri",
                "ordering": ["-payment_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "-payment_date"],
                        name="finance_cas_account_88372d_idx",
                    ),
                    models.Index(
                        fields=["source_module", "source_id"],
                        name="finance_cas_source__6b8a7f_idx",
                    ),
                    models.Index(
                        fields=["transaction_type", "status"],
                        name="finance_cas_transac_7e94b3_idx",
                    ),
                    models.Index(
                        fields=["transaction_number"],
                        name="finance_cas_transac_c36772_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CashFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "Günlük"),
                            ("weekly", "Haftalık"),
                            ("monthly", "Aylık"),
                            ("yearly", "Yıllık"),
                        ],
                        max_length=20,
                        verbose_name="Dönem Tipi",
                    ),
                ),
                ("period_start", models.DateField(verbose_name="Dönem Başlangıcı")),
                ("period_end", models.DateField(verbose_name="Dönem Bitişi")),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Açılış Bakiyesi",
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Kapanış Bakiyesi",
                    ),
                ),
                (
                    "total_income",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Toplam Gelir",
                    ),
                ),
                (
                    "total_expense",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Toplam Gider",
                    ),
                ),
                (
                    "net_flow",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Gelir - Gider",
                        max_digits=15,
                        verbose_name="Net Akış",
                    ),
                ),
                (
                    "income_count",
                    models.IntegerField(default=0, verbose_name="Gelir İşlem Sayısı"),
                ),
                (
                    "expense_count",
                    models.IntegerField(default=0, verbose_name="Gider İşlem Sayısı"),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Hesaplanma Tarihi"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_flows",
                        to="finance.cashaccount",
                        verbose_name="Kasa Hesabı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nakit Akışı",
                "verbose_name_plural": "Nakit Akışları",
                "ordering": ["-period_start", "-period_end"],
                "indexes": [
                    models.Index(
                        fields=["account", "period_type", "-period_start"],
                        name="finance_cas_account_d16772_idx",
                    )
                ],
                "unique_together": {
                    ("account", "period_type", "period_start", "period_end")
                },
            },
        ),
    ]
