# Generated by Django 4.2.11 on 2025-11-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction_customer_address_and_more'),
        ('reception', '0003_add_deleted_by_to_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationvoucher',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, help_text='Müşteriye gönderilecek token link için', max_length=64, null=True, unique=True, verbose_name='Erişim Token'),
        ),
        migrations.AddField(
            model_name='reservationvoucher',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Voucher için ödenecek tutar (0 ise rezervasyon kalan tutarı)', max_digits=12, verbose_name='Ödeme Tutarı'),
        ),
        migrations.AddField(
            model_name='reservationvoucher',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tamamlanma Tarihi'),
        ),
        migrations.AddField(
            model_name='reservationvoucher',
            name='payment_currency',
            field=models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AddField(
            model_name='reservationvoucher',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tarihi'),
        ),
        migrations.AddField(
            model_name='reservationvoucher',
            name='payment_info',
            field=models.JSONField(blank=True, default=dict, help_text='Ödeme detayları, kart bilgileri vb.', verbose_name='Ödeme Bilgileri'),
        ),
        migrations.AddField(
            model_name='reservationvoucher',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Kredi kartı, havale vb.', max_length=50, verbose_name='Ödeme Yöntemi'),
        ),
        migrations.AddField(
            model_name='reservationvoucher',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ödeme Bekliyor'), ('partial', 'Kısmi Ödendi'), ('paid', 'Ödendi'), ('failed', 'Ödeme Başarısız'), ('cancelled', 'İptal Edildi'), ('refunded', 'İade Edildi')], db_index=True, default='pending', max_length=20, verbose_name='Ödeme Durumu'),
        ),
        migrations.AddField(
            model_name='reservationvoucher',
            name='payment_transaction',
            field=models.ForeignKey(blank=True, help_text='Voucher için yapılan ödeme işlemi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='payments.paymenttransaction', verbose_name='Ödeme İşlemi'),
        ),
        migrations.AddField(
            model_name='reservationvoucher',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Token ne zaman geçersiz olacak', null=True, verbose_name='Token Geçerlilik Tarihi'),
        ),
        migrations.AlterField(
            model_name='reservationvoucher',
            name='sent_via',
            field=models.CharField(blank=True, choices=[('email', 'E-posta'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('link', 'Link')], max_length=20, verbose_name='Gönderim Yöntemi'),
        ),
        migrations.AddIndex(
            model_name='reservationvoucher',
            index=models.Index(fields=['access_token'], name='reception_r_access__dd3b3f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservationvoucher',
            index=models.Index(fields=['payment_status'], name='reception_r_payment_d47962_idx'),
        ),
    ]
