# Generated by Django 4.2.11 on 2025-11-14 21:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotelextraservice'),
        ('accounting', '0003_account_hotel_invoice_hotel_journalentry_hotel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reception', '0004_add_voucher_payment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndOfDayOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('operation_date', models.DateField(db_index=True, help_text='Gün sonu işleminin yapıldığı tarih', verbose_name='İşlem Tarihi')),
                ('program_date', models.DateField(db_index=True, help_text='İşlemin yapıldığı günün tarihi', verbose_name='Program Tarihi')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('rolled_back', 'Geri Alındı')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('is_async', models.BooleanField(default=False, help_text='Asenkron olarak çalıştırılsın mı?', verbose_name='Asenkron mu?')),
                ('automation_type', models.CharField(choices=[('scheduled', 'Zaman Planlı'), ('manual', 'Manuel'), ('automatic', 'Tam Otomatik')], db_index=True, default='manual', max_length=20, verbose_name='Otomasyon Türü')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='İşlem sırasında kullanılan ayarlar', verbose_name='İşlem Ayarları')),
                ('results', models.JSONField(blank=True, default=dict, help_text='İşlem sonuçları ve istatistikler', verbose_name='İşlem Sonuçları')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Zamanı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('error_message', models.TextField(blank=True, help_text='İşlem sırasında oluşan hatalar', verbose_name='Hata Mesajı')),
                ('rollback_data', models.JSONField(blank=True, default=dict, help_text='Geri alma işlemi için gerekli veriler', verbose_name='Rollback Verileri')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Ek Bilgiler')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_end_of_day_operations', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_of_day_operations', to='hotels.hotel', verbose_name='Otel')),
            ],
            options={
                'verbose_name': 'Gün Sonu İşlemi',
                'verbose_name_plural': 'Gün Sonu İşlemleri',
                'ordering': ['-operation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EndOfDaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('stop_if_room_price_zero', models.BooleanField(default=True, help_text='Sıfır fiyatlı oda varsa gün sonu işlemini durdur', verbose_name='Oda Fiyatı SIFIR İse Durdur!')),
                ('stop_if_advance_folio_balance_not_zero', models.BooleanField(default=True, help_text='Peşin ödemeli rezervasyonda bakiye varsa durdur', verbose_name='Peşin Folyo Balansı Sıfır Değilse Durdur!')),
                ('check_checkout_folios', models.BooleanField(default=True, help_text='Check-out yapılmış folyoları kontrol et', verbose_name='Checkout Olmuş Folyoları Kontrol Et!')),
                ('cancel_no_show_reservations', models.BooleanField(default=False, help_text='No-show rezervasyonları iptal et veya yarına al', verbose_name='Gelmeyen Rezervasyonları İptal Et veya Yarına Al!')),
                ('no_show_action', models.CharField(choices=[('cancel', 'İptal Et'), ('move_to_tomorrow', 'Yarına Al')], default='cancel', help_text='No-show rezervasyonları için yapılacak işlem', max_length=20, verbose_name='No-Show İşlemi')),
                ('extend_non_checkout_reservations', models.BooleanField(default=False, help_text='Check-out yapılmamış rezervasyonları otomatik uzat', verbose_name='CheckOut Olmamış Konaklayanları UZAT!')),
                ('extend_days', models.IntegerField(default=1, help_text='Kaç gün uzatılacak?', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Uzatma Gün Sayısı')),
                ('cancel_room_change_plans', models.BooleanField(default=False, help_text='Planlanmış ama gerçekleşmemiş oda değişimlerini iptal et', verbose_name='Oda Değişim Planlarını İPTAL Et!')),
                ('auto_run_time', models.TimeField(blank=True, help_text='Gün sonu işleminin otomatik başlatılacağı saat (örn: 02:00)', null=True, verbose_name='Otomatik Çalışma Saati')),
                ('automation_type', models.CharField(choices=[('scheduled', 'Zaman Planlı'), ('manual', 'Manuel'), ('automatic', 'Tam Otomatik')], default='manual', help_text='Gün sonu işleminin nasıl çalıştırılacağı', max_length=20, verbose_name='Otomasyon Türü')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('enable_rollback', models.BooleanField(default=True, help_text='Hata durumunda geri alma işlemi yapılabilsin mi?', verbose_name='Rollback Aktif mi?')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_of_day_settings', to='hotels.hotel', verbose_name='Otel')),
            ],
            options={
                'verbose_name': 'Gün Sonu Ayarı',
                'verbose_name_plural': 'Gün Sonu Ayarları',
                'ordering': ['hotel__name'],
            },
        ),
        migrations.CreateModel(
            name='EndOfDayJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('entry_type', models.CharField(choices=[('revenue', 'Gelir'), ('expense', 'Gider'), ('transfer', 'Transfer')], db_index=True, max_length=20, verbose_name='Fiş Türü')),
                ('department', models.CharField(choices=[('room', 'Konaklama'), ('f&b', 'Yiyecek-İçecek'), ('spa', 'Spa'), ('extra', 'Ek Hizmetler')], db_index=True, max_length=20, verbose_name='Departman')),
                ('market_segment', models.CharField(blank=True, choices=[('direct', 'Direkt'), ('online', 'Online'), ('agency', 'Acente'), ('corporate', 'Kurumsal'), ('group', 'Grup'), ('walk_in', 'Gel-Al')], db_index=True, max_length=20, verbose_name='Pazar Segmenti')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tutar')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_of_day_operations', to='accounting.journalentry', verbose_name='Yevmiye Kaydı')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='reception.endofdayoperation', verbose_name='Gün Sonu İşlemi')),
            ],
            options={
                'verbose_name': 'Gün Sonu Muhasebe Fişi',
                'verbose_name_plural': 'Gün Sonu Muhasebe Fişleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EndOfDayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('report_type', models.CharField(choices=[('summary', 'Özet'), ('financial', 'Finansal'), ('operational', 'Operasyonel'), ('guest', 'Misafir'), ('management', 'Yönetim')], db_index=True, max_length=20, verbose_name='Rapor Türü')),
                ('report_data', models.JSONField(default=dict, help_text='Rapor içeriği (JSON)', verbose_name='Rapor Verileri')),
                ('report_file', models.FileField(blank=True, help_text='PDF/Excel rapor dosyası', null=True, upload_to='reception/end_of_day/reports/%Y/%m/', verbose_name='Rapor Dosyası')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('json', 'JSON'), ('csv', 'CSV')], default='pdf', max_length=10, verbose_name='Export Formatı')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('exported_to', models.JSONField(blank=True, default=list, help_text='Hangi sistemlere gönderildi?', verbose_name='Gönderildiği Sistemler')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reception.endofdayoperation', verbose_name='Gün Sonu İşlemi')),
            ],
            options={
                'verbose_name': 'Gün Sonu Raporu',
                'verbose_name_plural': 'Gün Sonu Raporları',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['operation', 'report_type'], name='reception_e_operati_fbbaff_idx'), models.Index(fields=['generated_at'], name='reception_e_generat_602e78_idx')],
            },
        ),
        migrations.CreateModel(
            name='EndOfDayOperationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('step_name', models.CharField(help_text='İşlem adımının adı', max_length=200, verbose_name='Adım Adı')),
                ('step_order', models.IntegerField(help_text='Adımın sırası (1, 2, 3, ...)', verbose_name='Sıra Numarası')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Zamanı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('result_data', models.JSONField(blank=True, default=dict, help_text='Adımın sonuç verileri', verbose_name='Sonuç Verileri')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('rollback_data', models.JSONField(blank=True, default=dict, verbose_name='Rollback Verileri')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='reception.endofdayoperation', verbose_name='Gün Sonu İşlemi')),
            ],
            options={
                'verbose_name': 'Gün Sonu İşlem Adımı',
                'verbose_name_plural': 'Gün Sonu İşlem Adımları',
                'ordering': ['operation', 'step_order'],
                'indexes': [models.Index(fields=['operation', 'step_order'], name='reception_e_operati_e1c91d_idx'), models.Index(fields=['operation', 'status'], name='reception_e_operati_e29ce3_idx')],
                'unique_together': {('operation', 'step_order')},
            },
        ),
        migrations.AddIndex(
            model_name='endofdayoperation',
            index=models.Index(fields=['hotel', 'operation_date'], name='reception_e_hotel_i_518dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='endofdayoperation',
            index=models.Index(fields=['hotel', 'status'], name='reception_e_hotel_i_e0056d_idx'),
        ),
        migrations.AddIndex(
            model_name='endofdayoperation',
            index=models.Index(fields=['operation_date', 'status'], name='reception_e_operati_2e990e_idx'),
        ),
        migrations.AddIndex(
            model_name='endofdayoperation',
            index=models.Index(fields=['automation_type'], name='reception_e_automat_8236c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='endofdayoperation',
            unique_together={('hotel', 'operation_date')},
        ),
        migrations.AddIndex(
            model_name='endofdayjournalentry',
            index=models.Index(fields=['operation', 'entry_type'], name='reception_e_operati_027d60_idx'),
        ),
        migrations.AddIndex(
            model_name='endofdayjournalentry',
            index=models.Index(fields=['operation', 'department'], name='reception_e_operati_d485db_idx'),
        ),
        migrations.AddIndex(
            model_name='endofdayjournalentry',
            index=models.Index(fields=['operation', 'market_segment'], name='reception_e_operati_e09fbe_idx'),
        ),
    ]
