# Generated by Django 4.2.11 on 2025-11-11 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="max_api_calls_per_day",
        ),
        migrations.RemoveField(
            model_name="package",
            name="max_hotels",
        ),
        migrations.RemoveField(
            model_name="package",
            name="max_reservations_per_month",
        ),
        migrations.RemoveField(
            model_name="package",
            name="max_rooms",
        ),
        migrations.RemoveField(
            model_name="package",
            name="max_storage_gb",
        ),
        migrations.RemoveField(
            model_name="package",
            name="max_users",
        ),
    ]
