# Generated by Django 4.2.11 on 2025-11-16 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(help_text='HTML formatında içerik girebilirsiniz', verbose_name='İçerik (HTML)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('priority', models.IntegerField(default=0, help_text='Yüksek sayı önce gösterilir', verbose_name='Öncelik')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(help_text='HTML formatında içerik girebilirsiniz', verbose_name='İçerik (HTML)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/', verbose_name='Resim')),
                ('link_url', models.URLField(blank=True, help_text='Tıklanınca gidilecek URL', verbose_name='Link URL')),
                ('link_text', models.CharField(blank=True, max_length=100, verbose_name='Link Metni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('priority', models.IntegerField(default=0, help_text='Yüksek sayı önce gösterilir', verbose_name='Öncelik')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Reklam',
                'verbose_name_plural': 'Reklamlar',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
