# Generated by Django 4.2.11 on 2025-11-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Gateway Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Gateway Kodu")),
                (
                    "gateway_type",
                    models.CharField(
                        choices=[
                            ("iyzico", "İyzico"),
                            ("paytr", "PayTR"),
                            ("nestpay", "NestPay"),
                            ("payu", "PayU"),
                            ("paymes", "Paymes"),
                            ("garanti", "Garanti Sanal Pos"),
                            ("isbank", "İş Bankası Sanal Pos"),
                            ("akbank", "Akbank Sanal Pos"),
                            ("ziraat", "Ziraat Bankası Sanal Pos"),
                            ("yapikredi", "Yapı Kredi Sanal Pos"),
                            ("stripe", "Stripe"),
                            ("other", "Diğer"),
                        ],
                        max_length=50,
                        verbose_name="Gateway Tipi",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("api_url", models.URLField(blank=True, verbose_name="API URL")),
                (
                    "test_api_url",
                    models.URLField(blank=True, verbose_name="Test API URL"),
                ),
                (
                    "supports_3d_secure",
                    models.BooleanField(
                        default=True, verbose_name="3D Secure Destekli"
                    ),
                ),
                (
                    "supports_installment",
                    models.BooleanField(default=False, verbose_name="Taksit Destekli"),
                ),
                (
                    "supports_refund",
                    models.BooleanField(default=True, verbose_name="İade Destekli"),
                ),
                (
                    "supports_recurring",
                    models.BooleanField(
                        default=False, verbose_name="Otomatik Ödeme Destekli"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_test_mode",
                    models.BooleanField(default=True, verbose_name="Test Modu"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Gateway Ayarları"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödeme Gateway",
                "verbose_name_plural": "Ödeme Gateway'leri",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="İşlem ID"
                    ),
                ),
                (
                    "order_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Sipariş ID"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Referans No"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Tutar"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("processing", "İşleniyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Başarısız"),
                            ("cancelled", "İptal Edildi"),
                            ("refunded", "İade Edildi"),
                            ("partially_refunded", "Kısmi İade"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        default="credit_card",
                        max_length=50,
                        verbose_name="Ödeme Yöntemi",
                    ),
                ),
                (
                    "installment_count",
                    models.IntegerField(default=1, verbose_name="Taksit Sayısı"),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Gateway Yanıtı"
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Gateway İşlem ID"
                    ),
                ),
                (
                    "card_bin",
                    models.CharField(blank=True, max_length=6, verbose_name="Kart BIN"),
                ),
                (
                    "card_last_four",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Son 4 Hane"
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Kart Tipi"
                    ),
                ),
                (
                    "is_3d_secure",
                    models.BooleanField(default=False, verbose_name="3D Secure"),
                ),
                (
                    "md_status",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="MD Status"
                    ),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Hata Kodu"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ödeme Tarihi"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "gateway",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="payments.paymentgateway",
                        verbose_name="Gateway",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödeme İşlemi",
                "verbose_name_plural": "Ödeme İşlemleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="Event Tipi"),
                ),
                ("payload", models.JSONField(default=dict, verbose_name="Payload")),
                ("headers", models.JSONField(default=dict, verbose_name="Headers")),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="İşlendi mi?"),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, verbose_name="İşleme Hatası"),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="payments.paymentgateway",
                        verbose_name="Gateway",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhooks",
                        to="payments.paymenttransaction",
                        verbose_name="İşlem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhook'lar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TenantPaymentGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API Key"
                    ),
                ),
                (
                    "secret_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Secret Key"
                    ),
                ),
                (
                    "merchant_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Merchant ID"
                    ),
                ),
                (
                    "store_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Store Key"
                    ),
                ),
                (
                    "use_3d_secure",
                    models.BooleanField(default=True, verbose_name="3D Secure Kullan"),
                ),
                (
                    "callback_url",
                    models.URLField(blank=True, verbose_name="Callback URL"),
                ),
                (
                    "enable_installment",
                    models.BooleanField(default=False, verbose_name="Taksit Aktif"),
                ),
                (
                    "max_installment",
                    models.IntegerField(default=12, verbose_name="Maksimum Taksit"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_test_mode",
                    models.BooleanField(default=True, verbose_name="Test Modu"),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ek Ayarlar"
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_configs",
                        to="payments.paymentgateway",
                        verbose_name="Gateway",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_gateways",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Ödeme Gateway",
                "verbose_name_plural": "Tenant Ödeme Gateway'leri",
                "ordering": ["tenant", "gateway"],
                "unique_together": {("tenant", "gateway")},
            },
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["transaction_id"], name="payments_pa_transac_c1fd68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["tenant", "status"], name="payments_pa_tenant__5f54b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["created_at"], name="payments_pa_created_a246c6_idx"
            ),
        ),
    ]
