# Generated by Django 4.2.11 on 2025-11-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="customer_address",
            field=models.TextField(blank=True, verbose_name="Müşteri Adres"),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="customer_city",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Müşteri Şehir"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="customer_country",
            field=models.CharField(
                default="Türkiye", max_length=100, verbose_name="Müşteri Ülke"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="customer_email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                max_length=254,
                verbose_name="Müşteri E-posta",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="customer_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Müşteri Adı"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="customer_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Müşteri Telefon"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="customer_surname",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Müşteri Soyadı"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="customer_zip_code",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Müşteri Posta Kodu"
            ),
        ),
    ]
