# Generated by Django 4.2.11 on 2025-11-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentgateway_gateway_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='accounting_payment_id',
            field=models.IntegerField(blank=True, help_text='Accounting modülündeki Payment ID', null=True, verbose_name='Muhasebe Ödeme ID'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='cash_transaction_id',
            field=models.IntegerField(blank=True, help_text='Finance modülündeki CashTransaction ID', null=True, verbose_name='Kasa İşlemi ID'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='refund_transaction_id',
            field=models.IntegerField(blank=True, help_text='Refunds modülündeki RefundTransaction ID', null=True, verbose_name='İade İşlemi ID'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='sales_record_id',
            field=models.IntegerField(blank=True, help_text='Sales modülündeki SalesRecord ID', null=True, verbose_name='Satış Kaydı ID'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='source_id',
            field=models.IntegerField(blank=True, help_text="Kaynak modülün kayıt ID'si", null=True, verbose_name='Kaynak ID'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='source_module',
            field=models.CharField(blank=True, help_text='reception, tours, sales, refunds vb.', max_length=50, verbose_name='Kaynak Modül'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='source_reference',
            field=models.CharField(blank=True, help_text='Rezervasyon no, Tur adı, Satış kaydı vb.', max_length=200, verbose_name='Kaynak Referans'),
        ),
    ]
