# Generated by Django 4.2.11 on 2025-11-14 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_tenantpaymentgateway_paytr_api_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminPaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('secret_key', models.CharField(blank=True, max_length=255, verbose_name='Secret Key')),
                ('merchant_id', models.CharField(blank=True, max_length=100, verbose_name='Merchant ID')),
                ('store_key', models.CharField(blank=True, max_length=255, verbose_name='Store Key')),
                ('use_3d_secure', models.BooleanField(default=True, verbose_name='3D Secure Kullan')),
                ('callback_url', models.URLField(blank=True, verbose_name='Callback URL')),
                ('enable_installment', models.BooleanField(default=False, verbose_name='Taksit Aktif')),
                ('max_installment', models.IntegerField(default=12, verbose_name='Maksimum Taksit')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_test_mode', models.BooleanField(default=True, verbose_name='Test Modu')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Ek Ayarlar')),
                ('paytr_api_type', models.CharField(blank=True, choices=[('direct', 'Direkt API'), ('iframe', 'iFrame API')], default='direct', help_text='PayTR için kullanılacak API tipi (Direkt API veya iFrame API)', max_length=20, verbose_name='PayTR API Tipi')),
                ('gateway', models.ForeignKey(limit_choices_to={'code__in': ['iyzico', 'paytr']}, on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_configs', to='payments.paymentgateway', verbose_name='Gateway')),
            ],
            options={
                'verbose_name': 'Super Admin Ödeme Gateway',
                'verbose_name_plural': "Super Admin Ödeme Gateway'leri",
                'ordering': ['gateway'],
                'unique_together': {('gateway',)},
            },
        ),
    ]
