# Generated by Django 4.2.11 on 2025-11-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotelextraservice'),
        ('channel_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpricing',
            name='room_price',
            field=models.ForeignKey(blank=True, help_text='Sistemdeki oda fiyatı ile bağlantı', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_pricings', to='hotels.roomprice', verbose_name='Oda Fiyatı'),
        ),
    ]
