# Generated by Django 4.2.11 on 2025-11-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_channeltemplate'),
        ('channel_management', '0002_channelpricing_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelconfiguration',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='modules.channeltemplate', verbose_name='Kanal Şablonu'),
        ),
        migrations.DeleteModel(
            name='ChannelTemplate',
        ),
    ]
