# Generated by Django 4.2.11 on 2025-11-11 11:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenant_core", "0003_customer_customernote_customerloyaltyhistory_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BedType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Yatak Tipi")),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="İkon"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
            ],
            options={
                "verbose_name": "Yatak Tipi",
                "verbose_name_plural": "Yatak Tipleri",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BoardType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Pansiyon Tipi"),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
            ],
            options={
                "verbose_name": "Pansiyon Tipi",
                "verbose_name_plural": "Pansiyon Tipleri",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Otel Adı")),
                ("code", models.SlugField(verbose_name="Otel Kodu")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "star_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 Yıldız"),
                            (2, "2 Yıldız"),
                            (3, "3 Yıldız"),
                            (4, "4 Yıldız"),
                            (5, "5 Yıldız"),
                        ],
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Yıldız",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-posta"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "telegram",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Telegram"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Web Sitesi")),
                ("address", models.TextField(verbose_name="Adres")),
                (
                    "district",
                    models.CharField(blank=True, max_length=100, verbose_name="İlçe"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Posta Kodu"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Türkiye", max_length=100, verbose_name="Ülke"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Enlem",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Boylam",
                    ),
                ),
                (
                    "total_rooms",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Toplam Oda Sayısı",
                    ),
                ),
                (
                    "total_beds",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Toplam Yatak Sayısı",
                    ),
                ),
                (
                    "check_in_time",
                    models.TimeField(default="14:00", verbose_name="Check-in Saati"),
                ),
                (
                    "check_out_time",
                    models.TimeField(default="12:00", verbose_name="Check-out Saati"),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hotels/main/",
                        verbose_name="Ana Sayfa Resmi",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hotels/logo/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hotels/favicon/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "detail_description",
                    models.TextField(
                        blank=True,
                        help_text="Otel hakkında detaylı bilgi",
                        verbose_name="Detay Açıklama",
                    ),
                ),
                (
                    "policies",
                    models.TextField(
                        blank=True,
                        help_text="İptal, check-in/out, vb. politikalar",
                        verbose_name="Otel Politikaları",
                    ),
                ),
                (
                    "concept_description",
                    models.TextField(
                        blank=True,
                        help_text="Otel konsepti ve özellikleri",
                        verbose_name="Konsept Açıklama",
                    ),
                ),
                (
                    "youtube_video_url",
                    models.URLField(blank=True, verbose_name="YouTube Video Linki"),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="hotels/videos/",
                        verbose_name="Video Dosyası",
                    ),
                ),
                (
                    "social_media",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"facebook": "url", "instagram": "url", "twitter": "url"}',
                        verbose_name="Sosyal Medya Hesapları",
                    ),
                ),
                (
                    "services",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Otel hizmetleri listesi",
                        verbose_name="Hizmetler",
                    ),
                ),
                (
                    "amenities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Otel olanakları listesi",
                        verbose_name="Olanaklar",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="İlk otel varsayılan olarak işaretlenir",
                        verbose_name="Varsayılan Otel mi?",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Öne Çıkan mı?"),
                ),
                (
                    "is_homepage_visible",
                    models.BooleanField(
                        default=True, verbose_name="Anasayfada Görünür mü?"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Otel özel ayarları (dil, para birimi, vb.)",
                        verbose_name="Otel Ayarları",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otel",
                "verbose_name_plural": "Oteller",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HotelFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Özellik Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="İkon"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Örn: Genel, Eğlence, Spor, vb.",
                        max_length=50,
                        verbose_name="Kategori",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
            ],
            options={
                "verbose_name": "Otel Özelliği",
                "verbose_name_plural": "Otel Özellikleri",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HotelRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Bölge Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
            ],
            options={
                "verbose_name": "Otel Bölgesi",
                "verbose_name_plural": "Otel Bölgeleri",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="HotelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Otel Türü")),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome class veya emoji",
                        max_length=50,
                        verbose_name="İkon",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
            ],
            options={
                "verbose_name": "Otel Türü",
                "verbose_name_plural": "Otel Türleri",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Oda Adı")),
                ("code", models.SlugField(verbose_name="Oda Kodu")),
                (
                    "max_adults",
                    models.IntegerField(
                        default=2,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Maksimum Yetişkin",
                    ),
                ),
                (
                    "max_children",
                    models.IntegerField(
                        default=2,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Maksimum Çocuk",
                    ),
                ),
                (
                    "max_total_capacity",
                    models.IntegerField(
                        default=4,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Maksimum Toplam Kapasite",
                    ),
                ),
                (
                    "area_sqm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Metrekare",
                    ),
                ),
                (
                    "bed_count",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Yatak Sayısı",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="rooms/main/",
                        verbose_name="Ana Sayfa Resmi",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, verbose_name="Video URL (YouTube)"),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="rooms/videos/",
                        verbose_name="Video Dosyası",
                    ),
                ),
                (
                    "virtual_3d_url",
                    models.URLField(blank=True, verbose_name="3D Virtual Tour URL"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Detay Açıklama"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Öne Çıkan mı?"),
                ),
                (
                    "is_homepage_visible",
                    models.BooleanField(
                        default=True, verbose_name="Anasayfada Görünür mü?"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "room_count",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Oda Sayısı",
                    ),
                ),
                (
                    "bed_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rooms",
                        to="hotels.bedtype",
                        verbose_name="Yatak Tipi",
                    ),
                ),
                (
                    "board_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rooms",
                        to="hotels.boardtype",
                        verbose_name="Pansiyon Tipi",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hotels.hotel",
                        verbose_name="Otel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oda",
                "verbose_name_plural": "Odalar",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Özellik Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="İkon"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
            ],
            options={
                "verbose_name": "Oda Özelliği",
                "verbose_name_plural": "Oda Özellikleri",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "pricing_type",
                    models.CharField(
                        choices=[
                            ("fixed_room", "Sabit Oda Fiyatı"),
                            ("per_person", "Kişi Çarpanı"),
                        ],
                        default="fixed_room",
                        max_length=20,
                        verbose_name="Fiyatlama Tipi",
                    ),
                ),
                (
                    "basic_nightly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Basic Gecelik Fiyat",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "adult_multipliers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"1": 1.0, "2": 1.8, "3": 2.5} - Kişi sayısına göre çarpan',
                        verbose_name="Yetişkin Çarpanları",
                    ),
                ),
                (
                    "child_fixed_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.5"),
                        help_text="Çocuk için sabit çarpan (örn: 0.5 = yarı fiyat)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Çocuk Sabit Çarpan",
                    ),
                ),
                (
                    "child_age_range",
                    models.CharField(
                        default="0-12",
                        help_text="Örn: 0-12",
                        max_length=20,
                        verbose_name="Çocuk Yaş Aralığı",
                    ),
                ),
                (
                    "free_children_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ücretsiz Çocuk Sayısı",
                    ),
                ),
                (
                    "free_children_rules",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"age_range": "0-6", "count": 2, "adult_required": 2}]',
                        verbose_name="Ücretsiz Çocuk Kuralları",
                    ),
                ),
                (
                    "total_discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Toplam İndirim Oranı (%)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="hotels.room",
                        verbose_name="Oda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oda Fiyatı",
                "verbose_name_plural": "Oda Fiyatları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Oda Tipi")),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="İkon"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
            ],
            options={
                "verbose_name": "Oda Tipi",
                "verbose_name_plural": "Oda Tipleri",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="rooms/gallery/", verbose_name="Resim"),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Başlık"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="hotels.room",
                        verbose_name="Oda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oda Resmi",
                "verbose_name_plural": "Oda Resimleri",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="room",
            name="room_features",
            field=models.ManyToManyField(
                blank=True,
                related_name="rooms",
                to="hotels.roomfeature",
                verbose_name="Oda Özellikleri",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rooms",
                to="hotels.roomtype",
                verbose_name="Oda Tipi",
            ),
        ),
        migrations.CreateModel(
            name="HotelUserPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "permission_level",
                    models.CharField(
                        choices=[
                            ("view", "Görüntüleme"),
                            ("manage", "Yönetim"),
                            ("admin", "Yönetici"),
                        ],
                        default="view",
                        max_length=20,
                        verbose_name="Yetki Seviyesi",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Atanma Tarihi"
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_hotel_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atayan Kullanıcı",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="hotels.hotel",
                        verbose_name="Otel",
                    ),
                ),
                (
                    "tenant_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotel_permissions",
                        to="tenant_core.tenantuser",
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otel Kullanıcı Yetkisi",
                "verbose_name_plural": "Otel Kullanıcı Yetkileri",
            },
        ),
        migrations.CreateModel(
            name="HotelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="hotels/gallery/", verbose_name="Resim"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Başlık"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="hotels.hotel",
                        verbose_name="Otel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otel Resmi",
                "verbose_name_plural": "Otel Resimleri",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HotelCity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Şehir Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cities",
                        to="hotels.hotelregion",
                        verbose_name="Bölge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otel Şehri",
                "verbose_name_plural": "Otel Şehirleri",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="hotel",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hotels",
                to="hotels.hotelcity",
                verbose_name="Şehir",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_features",
            field=models.ManyToManyField(
                blank=True,
                related_name="hotels",
                to="hotels.hotelfeature",
                verbose_name="Otel Özellikleri",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="hotel_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hotels",
                to="hotels.hoteltype",
                verbose_name="Otel Türü",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hotels",
                to="hotels.hotelregion",
                verbose_name="Bölge",
            ),
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "floor_number",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Kat Numarası",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Örn: Zemin Kat, 1. Kat, vb.",
                        max_length=100,
                        verbose_name="Kat Adı",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="hotels.hotel",
                        verbose_name="Otel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kat",
                "verbose_name_plural": "Katlar",
                "ordering": ["floor_number"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Blok Adı")),
                ("code", models.SlugField(verbose_name="Blok Kodu")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="hotels.hotel",
                        verbose_name="Otel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blok",
                "verbose_name_plural": "Bloklar",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomSpecialPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_index=True, verbose_name="Başlangıç Tarihi"),
                ),
                (
                    "end_date",
                    models.DateField(db_index=True, verbose_name="Bitiş Tarihi"),
                ),
                (
                    "weekday_prices",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"monday": {"per_person": 100, "fixed": 200}, "saturday": {"per_person": 150, "fixed": 300}}',
                        verbose_name="Gün Bazlı Fiyatlar",
                    ),
                ),
                (
                    "weekend_price_per_person",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Hafta Sonu Kişi Başı Fiyat",
                    ),
                ),
                (
                    "weekend_fixed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Hafta Sonu Sabit Fiyat",
                    ),
                ),
                (
                    "weekday_price_per_person",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Hafta İçi Kişi Başı Fiyat",
                    ),
                ),
                (
                    "weekday_fixed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Hafta İçi Sabit Fiyat",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "room_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_prices",
                        to="hotels.roomprice",
                        verbose_name="Oda Fiyatı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Özel Fiyat",
                "verbose_name_plural": "Özel Fiyatlar",
                "ordering": ["start_date"],
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date", "is_active"],
                        name="hotels_room_start_d_802995_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoomSeasonalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_index=True, verbose_name="Başlangıç Tarihi"),
                ),
                (
                    "end_date",
                    models.DateField(db_index=True, verbose_name="Bitiş Tarihi"),
                ),
                (
                    "price_per_person",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Kişi Başı Fiyat",
                    ),
                ),
                (
                    "fixed_room_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Sabit Oda Fiyatı",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "room_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasonal_prices",
                        to="hotels.roomprice",
                        verbose_name="Oda Fiyatı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sezonluk Fiyat",
                "verbose_name_plural": "Sezonluk Fiyatlar",
                "ordering": ["start_date"],
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date", "is_active"],
                        name="hotels_room_start_d_6ef1cc_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoomNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Oda Numarası"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Boş"),
                            ("occupied", "Dolu"),
                            ("clean", "Temiz"),
                            ("dirty", "Kirli"),
                            ("cleaning_pending", "Temizlik Bekliyor"),
                            ("maintenance", "Bakımda"),
                            ("out_of_order", "Hizmet Dışı"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Oda hakkında özel notlar",
                        verbose_name="Notlar",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_numbers",
                        to="hotels.block",
                        verbose_name="Blok",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_numbers",
                        to="hotels.floor",
                        verbose_name="Kat",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_numbers",
                        to="hotels.hotel",
                        verbose_name="Otel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="Bu numara hangi oda tipine ait",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_numbers",
                        to="hotels.room",
                        verbose_name="Oda Tipi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oda Numarası",
                "verbose_name_plural": "Oda Numaraları",
                "ordering": ["floor__floor_number", "number"],
                "indexes": [
                    models.Index(
                        fields=["hotel", "status", "is_active"],
                        name="hotels_room_hotel_i_f29757_idx",
                    ),
                    models.Index(
                        fields=["room", "status"], name="hotels_room_room_id_be711e_idx"
                    ),
                    models.Index(
                        fields=["number"], name="hotels_room_number_0e6dd8_idx"
                    ),
                ],
                "unique_together": {("hotel", "number")},
            },
        ),
        migrations.CreateModel(
            name="RoomChannelPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "channel_code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Kanal Kodu"
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(max_length=200, verbose_name="Kanal Adı"),
                ),
                (
                    "price_per_person",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Kişi Başı Fiyat",
                    ),
                ),
                (
                    "fixed_room_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Sabit Oda Fiyatı",
                    ),
                ),
                (
                    "markup_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Kanal için ek fiyat artışı",
                        max_digits=5,
                        verbose_name="Markup Oranı (%)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "room_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_prices",
                        to="hotels.roomprice",
                        verbose_name="Oda Fiyatı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kanal Fiyatı",
                "verbose_name_plural": "Kanal Fiyatları",
                "indexes": [
                    models.Index(
                        fields=["channel_code", "is_active"],
                        name="hotels_room_channel_c8c8ca_idx",
                    )
                ],
                "unique_together": {("room_price", "channel_code")},
            },
        ),
        migrations.CreateModel(
            name="RoomCampaignPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Kampanya Adı")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "start_date",
                    models.DateField(db_index=True, verbose_name="Başlangıç Tarihi"),
                ),
                (
                    "end_date",
                    models.DateField(db_index=True, verbose_name="Bitiş Tarihi"),
                ),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("stay_nights", "X Gece Kal"),
                            ("early_booking", "Erken Rezervasyon"),
                            ("last_minute", "Son Dakika"),
                            ("group", "Grup İndirimi"),
                            ("custom", "Özel Kampanya"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="Kampanya Tipi",
                    ),
                ),
                (
                    "campaign_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"stay_nights": 7, "discount_percent": 10, "discount_amount": 100}',
                        verbose_name="Kampanya Kuralları",
                    ),
                ),
                (
                    "price_per_person",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Kişi Başı Fiyat",
                    ),
                ),
                (
                    "fixed_room_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Sabit Oda Fiyatı",
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="İndirim Oranı (%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="İndirim Tutarı",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "room_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_prices",
                        to="hotels.roomprice",
                        verbose_name="Oda Fiyatı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kampanya Fiyatı",
                "verbose_name_plural": "Kampanya Fiyatları",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date", "is_active"],
                        name="hotels_room_start_d_e0d344_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoomAgencyPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "agency_id",
                    models.IntegerField(db_index=True, verbose_name="Acente ID"),
                ),
                (
                    "agency_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Acente Adı"
                    ),
                ),
                (
                    "price_per_person",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Kişi Başı Fiyat",
                    ),
                ),
                (
                    "fixed_room_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Sabit Oda Fiyatı",
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Komisyon Oranı (%)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "room_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agency_prices",
                        to="hotels.roomprice",
                        verbose_name="Oda Fiyatı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acente Fiyatı",
                "verbose_name_plural": "Acente Fiyatları",
                "indexes": [
                    models.Index(
                        fields=["agency_id", "is_active"],
                        name="hotels_room_agency__98780b_idx",
                    )
                ],
                "unique_together": {("room_price", "agency_id")},
            },
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["hotel", "is_active"], name="hotels_room_hotel_i_8edaf3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["room_type", "is_active"], name="hotels_room_room_ty_6fa95d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(fields=["code"], name="hotels_room_code_f5cdba_idx"),
        ),
        migrations.AddIndex(
            model_name="hoteluserpermission",
            index=models.Index(
                fields=["tenant_user", "is_active"],
                name="hotels_hote_tenant__ffe390_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hoteluserpermission",
            index=models.Index(
                fields=["hotel", "is_active"], name="hotels_hote_hotel_i_5bae9d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hoteluserpermission",
            unique_together={("tenant_user", "hotel")},
        ),
        migrations.AddIndex(
            model_name="hotel",
            index=models.Index(
                fields=["code", "is_active"], name="hotels_hote_code_1b0a2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hotel",
            index=models.Index(
                fields=["city", "is_active"], name="hotels_hote_city_id_fb7985_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hotel",
            index=models.Index(
                fields=["region", "is_active"], name="hotels_hote_region__325744_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hotel",
            index=models.Index(
                fields=["is_default", "is_active"],
                name="hotels_hote_is_defa_8d666d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="floor",
            unique_together={("hotel", "floor_number")},
        ),
        migrations.AlterUniqueTogether(
            name="block",
            unique_together={("hotel", "code")},
        ),
    ]
