# Generated by Django 4.2.11 on 2025-11-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bedtype",
            options={
                "ordering": ["hotel", "sort_order", "name"],
                "verbose_name": "Yatak Tipi",
                "verbose_name_plural": "Yatak Tipleri",
            },
        ),
        migrations.AlterModelOptions(
            name="boardtype",
            options={
                "ordering": ["hotel", "sort_order", "name"],
                "verbose_name": "Pansiyon Tipi",
                "verbose_name_plural": "Pansiyon Tipleri",
            },
        ),
        migrations.AlterModelOptions(
            name="roomfeature",
            options={
                "ordering": ["hotel", "sort_order", "name"],
                "verbose_name": "Oda Özelliği",
                "verbose_name_plural": "Oda Özellikleri",
            },
        ),
        migrations.AlterModelOptions(
            name="roomtype",
            options={
                "ordering": ["hotel", "sort_order", "name"],
                "verbose_name": "Oda Tipi",
                "verbose_name_plural": "Oda Tipleri",
            },
        ),
        migrations.AddField(
            model_name="bedtype",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bed_types",
                to="hotels.hotel",
                verbose_name="Otel",
            ),
        ),
        migrations.AddField(
            model_name="boardtype",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="board_types",
                to="hotels.hotel",
                verbose_name="Otel",
            ),
        ),
        migrations.AddField(
            model_name="roomfeature",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_features",
                to="hotels.hotel",
                verbose_name="Otel",
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_types",
                to="hotels.hotel",
                verbose_name="Otel",
            ),
        ),
        migrations.AlterField(
            model_name="bedtype",
            name="code",
            field=models.SlugField(verbose_name="Kod"),
        ),
        migrations.AlterField(
            model_name="boardtype",
            name="code",
            field=models.SlugField(verbose_name="Kod"),
        ),
        migrations.AlterField(
            model_name="roomfeature",
            name="code",
            field=models.SlugField(verbose_name="Kod"),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="code",
            field=models.SlugField(verbose_name="Kod"),
        ),
        migrations.AlterUniqueTogether(
            name="bedtype",
            unique_together={("hotel", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="boardtype",
            unique_together={("hotel", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="roomfeature",
            unique_together={("hotel", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="roomtype",
            unique_together={("hotel", "code")},
        ),
        migrations.AddIndex(
            model_name="bedtype",
            index=models.Index(
                fields=["hotel", "is_active"], name="hotels_bedt_hotel_i_7ce1cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="boardtype",
            index=models.Index(
                fields=["hotel", "is_active"], name="hotels_boar_hotel_i_44623b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roomfeature",
            index=models.Index(
                fields=["hotel", "is_active"], name="hotels_room_hotel_i_e6fa3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roomtype",
            index=models.Index(
                fields=["hotel", "is_active"], name="hotels_room_hotel_i_898f3f_idx"
            ),
        ),
    ]
