# Generated by Django 4.2.11 on 2025-11-11 21:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0003_make_hotel_fields_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelExtraService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Hizmet Adı")),
                ("code", models.SlugField(blank=True, verbose_name="Kod")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Hizmet hakkında detaylı bilgi",
                        verbose_name="Açıklama",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hizmet fiyatı",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Fiyat",
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("per_person", "Kişi Başı"),
                            ("fixed", "Tek Seferlik / Sabit"),
                            ("per_night", "Gece Başı"),
                            ("per_room", "Oda Başı"),
                        ],
                        default="fixed",
                        help_text="Fiyatlandırma şekli",
                        max_length=20,
                        verbose_name="Fiyatlandırma Tipi",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY",
                        help_text="TRY, USD, EUR, vb.",
                        max_length=3,
                        verbose_name="Para Birimi",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_services",
                        to="hotels.hotel",
                        verbose_name="Otel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ekstra Hizmet",
                "verbose_name_plural": "Ekstra Hizmetler",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["hotel", "is_active"],
                        name="hotels_hote_hotel_i_8470ae_idx",
                    ),
                    models.Index(
                        fields=["code", "is_active"], name="hotels_hote_code_41aab3_idx"
                    ),
                ],
                "unique_together": {("hotel", "code")},
            },
        ),
    ]
