# Generated by Django 4.2.11 on 2025-11-10 14:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Hesap planı kodu (örn: 100, 120, 600)",
                        max_length=20,
                        unique=True,
                        verbose_name="Hesap Kodu",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Hesap Adı")),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Aktif"),
                            ("liability", "Pasif"),
                            ("equity", "Özsermaye"),
                            ("revenue", "Gelir"),
                            ("expense", "Gider"),
                        ],
                        max_length=20,
                        verbose_name="Hesap Tipi",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("TRY", "Türk Lirası"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                        ],
                        default="TRY",
                        max_length=3,
                        verbose_name="Para Birimi",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        help_text="Hesap hiyerarşi seviyesi (1, 2, 3, ...)",
                        verbose_name="Seviye",
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Açılış Bakiyesi",
                    ),
                ),
                (
                    "debit_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Otomatik hesaplanır",
                        max_digits=15,
                        verbose_name="Borç Bakiyesi",
                    ),
                ),
                (
                    "credit_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Otomatik hesaplanır",
                        max_digits=15,
                        verbose_name="Alacak Bakiyesi",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Sistem hesapları silinemez",
                        verbose_name="Sistem Hesabı mı?",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Ayarlar"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Hesap hiyerarşisi için",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="accounting.account",
                        verbose_name="Üst Hesap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hesap",
                "verbose_name_plural": "Hesap Planı",
                "ordering": ["code", "name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        help_text="Otomatik oluşturulur",
                        max_length=50,
                        unique=True,
                        verbose_name="Fatura No",
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("sales", "Satış Faturası"),
                            ("purchase", "Alış Faturası"),
                            ("expense", "Gider Faturası"),
                        ],
                        max_length=20,
                        verbose_name="Fatura Tipi",
                    ),
                ),
                (
                    "invoice_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fatura Tarihi"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Vade Tarihi"),
                ),
                (
                    "customer_name",
                    models.CharField(
                        max_length=200, verbose_name="Müşteri/Tedarikçi Adı"
                    ),
                ),
                (
                    "customer_tax_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Vergi No/TC"
                    ),
                ),
                (
                    "customer_address",
                    models.TextField(blank=True, verbose_name="Adres"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-posta"
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Ara Toplam",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=20,
                        max_digits=5,
                        verbose_name="KDV Oranı (%)",
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="KDV Tutarı",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="İndirim Tutarı",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Toplam Tutar",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Ödenen Tutar",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("sent", "Gönderildi"),
                            ("paid", "Ödendi"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "source_module",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Kaynak Modül"
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Kaynak ID"
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Kaynak Referans"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "attachments",
                    models.JSONField(blank=True, default=list, verbose_name="Ekler"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ek Bilgiler"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura",
                "verbose_name_plural": "Faturalar",
                "ordering": ["-invoice_date", "-invoice_number"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "entry_number",
                    models.CharField(
                        help_text="Otomatik oluşturulur",
                        max_length=50,
                        unique=True,
                        verbose_name="Yevmiye No",
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Kayıt Tarihi"
                    ),
                ),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "source_module",
                    models.CharField(
                        blank=True,
                        help_text="tours, reservations, finance vb.",
                        max_length=50,
                        verbose_name="Kaynak Modül",
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Kaynak ID"
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Kaynak Referans"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("posted", "Kaydedildi"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kayıt Tarihi"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "attachments",
                    models.JSONField(blank=True, default=list, verbose_name="Ekler"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ek Bilgiler"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_journal_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_journal_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kaydeden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yevmiye Kaydı",
                "verbose_name_plural": "Yevmiye Kayıtları",
                "ordering": ["-entry_date", "-entry_number"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntryLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Borç",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Alacak",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Açıklama"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journal_entry_lines",
                        to="accounting.account",
                        verbose_name="Hesap",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.journalentry",
                        verbose_name="Yevmiye Kaydı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yevmiye Kayıt Satırı",
                "verbose_name_plural": "Yevmiye Kayıt Satırları",
                "ordering": ["journal_entry", "id"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=200, verbose_name="Ürün/Hizmet Adı"),
                ),
                (
                    "item_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Ürün/Hizmet Kodu"
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        verbose_name="Miktar",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Birim Fiyat"
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="İndirim Oranı (%)",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Satır Toplamı"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="accounting.invoice",
                        verbose_name="Fatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fatura Satırı",
                "verbose_name_plural": "Fatura Satırları",
                "ordering": ["invoice", "id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(
                        help_text="Otomatik oluşturulur",
                        max_length=50,
                        unique=True,
                        verbose_name="Ödeme No",
                    ),
                ),
                (
                    "payment_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Ödeme Tarihi"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tutar",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Nakit"),
                            ("bank_transfer", "Banka Havalesi"),
                            ("credit_card", "Kredi Kartı"),
                            ("check", "Çek"),
                            ("digital_wallet", "Dijital Cüzdan"),
                            ("other", "Diğer"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="Ödeme Yöntemi",
                    ),
                ),
                (
                    "cash_account_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Finance modülündeki CashAccount ID",
                        null=True,
                        verbose_name="Kasa Hesabı ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "source_module",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Kaynak Modül"
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Kaynak ID"
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Kaynak Referans"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "attachments",
                    models.JSONField(blank=True, default=list, verbose_name="Ekler"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ek Bilgiler"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="accounting.invoice",
                        verbose_name="Fatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ödeme",
                "verbose_name_plural": "Ödemeler",
                "ordering": ["-payment_date", "-payment_number"],
                "indexes": [
                    models.Index(
                        fields=["payment_date", "status"],
                        name="accounting__payment_80cd65_idx",
                    ),
                    models.Index(
                        fields=["invoice"], name="accounting__invoice_429221_idx"
                    ),
                    models.Index(
                        fields=["source_module", "source_id"],
                        name="accounting__source__31f150_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["entry_date", "status"], name="accounting__entry_d_68b453_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["source_module", "source_id"],
                name="accounting__source__ee2000_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(
                fields=["entry_number"], name="accounting__entry_n_734b5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_date", "status"], name="accounting__invoice_70b7df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="accounting__invoice_f5b9b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["source_module", "source_id"],
                name="accounting__source__37553d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["code"], name="accounting__code_c93a8f_idx"),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["account_type"], name="accounting__account_889d6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["parent"], name="accounting__parent__da6035_idx"
            ),
        ),
    ]
