# Generated by Django 4.2.11 on 2025-11-09 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("modules", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Yetki Adı")),
                ("code", models.SlugField(verbose_name="Kod")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("view", "Görüntüleme"),
                            ("add", "Ekleme"),
                            ("edit", "Düzenleme"),
                            ("delete", "Silme"),
                            ("export", "Dışa Aktarma"),
                            ("import", "İçe Aktarma"),
                            ("approve", "Onaylama"),
                            ("cancel", "İptal Etme"),
                            ("other", "Diğer"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Yetki Tipi",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Sistem yetkileri silinemez",
                        verbose_name="Sistem Yetkisi mi?",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Ayarlar"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_permissions",
                        to="modules.module",
                        verbose_name="Modül",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yetki",
                "verbose_name_plural": "Yetkiler",
                "ordering": ["module", "sort_order", "name"],
                "unique_together": {("module", "code")},
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Rol Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "icon",
                    models.CharField(
                        default="🛡️",
                        help_text="Emoji veya Font Awesome class",
                        max_length=50,
                        verbose_name="İkon",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Sistem rolleri silinemez",
                        verbose_name="Sistem Rolü mü?",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Ayarlar"),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roller",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Kullanıcı Tipi Adı"),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "icon",
                    models.CharField(
                        default="👤",
                        help_text="Emoji veya Font Awesome class",
                        max_length=50,
                        verbose_name="İkon",
                    ),
                ),
                (
                    "dashboard_url",
                    models.CharField(
                        blank=True,
                        help_text="Bu kullanıcı tipi için özel dashboard URL'i",
                        max_length=200,
                        verbose_name="Dashboard URL",
                    ),
                ),
                (
                    "panel_template",
                    models.CharField(
                        blank=True,
                        help_text="Bu kullanıcı tipi için özel template",
                        max_length=200,
                        verbose_name="Panel Template",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Ayarlar"),
                ),
                (
                    "default_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_for_user_types",
                        to="tenant_core.role",
                        verbose_name="Varsayılan Rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Tipi",
                "verbose_name_plural": "Kullanıcı Tipleri",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TenantUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Departman"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Pozisyon"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Giriş"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Kullanıcı Ayarları"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Django User",
                    ),
                ),
                (
                    "user_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="tenant_core.usertype",
                        verbose_name="Kullanıcı Tipi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Kullanıcı",
                "verbose_name_plural": "Tenant Kullanıcıları",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Atanma Tarihi"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Ayarlar"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atayan Kullanıcı",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="tenant_core.role",
                        verbose_name="Rol",
                    ),
                ),
                (
                    "tenant_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="tenant_core.tenantuser",
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Rolü",
                "verbose_name_plural": "Kullanıcı Rolleri",
                "ordering": ["tenant_user", "role"],
                "unique_together": {("tenant_user", "role")},
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Atanma Tarihi"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Özel Ayarlar"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="tenant_core.permission",
                        verbose_name="Yetki",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="tenant_core.role",
                        verbose_name="Rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol Yetkisi",
                "verbose_name_plural": "Rol Yetkileri",
                "ordering": ["role", "permission"],
                "unique_together": {("role", "permission")},
            },
        ),
    ]
