# Generated by Django 4.2.11 on 2025-11-10 19:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenant_core", "0002_userpermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "customer_code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Müşteri Kodu",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ad")),
                ("last_name", models.CharField(max_length=100, verbose_name="Soyad")),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Müşteri eşleştirme için kullanılır",
                        max_length=254,
                        verbose_name="E-posta",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        help_text="Müşteri eşleştirme için kullanılır",
                        max_length=20,
                        verbose_name="Telefon",
                    ),
                ),
                (
                    "tc_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Müşteri eşleştirme için kullanılır",
                        max_length=11,
                        verbose_name="TC Kimlik No",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adres")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Şehir"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Türkiye", max_length=100, verbose_name="Ülke"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Posta Kodu"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Doğum Tarihi"
                    ),
                ),
                (
                    "special_dates",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Örn: [{"date": "2024-12-25", "name": "Evlilik Yıldönümü"}]',
                        verbose_name="Özel Günler",
                    ),
                ),
                (
                    "loyalty_points",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Sadakat Puanı",
                    ),
                ),
                (
                    "total_reservations",
                    models.IntegerField(
                        default=0,
                        help_text="Tüm modüllerden toplam rezervasyon sayısı",
                        verbose_name="Toplam Rezervasyon",
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tüm modüllerden toplam harcama",
                        max_digits=12,
                        verbose_name="Toplam Harcama",
                    ),
                ),
                (
                    "vip_level",
                    models.CharField(
                        choices=[
                            ("regular", "Normal"),
                            ("silver", "Gümüş (5+ rezervasyon)"),
                            ("gold", "Altın (10+ rezervasyon)"),
                            ("platinum", "Platin (20+ rezervasyon)"),
                            ("diamond", "Elmas (50+ rezervasyon)"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="VIP Seviyesi",
                    ),
                ),
                (
                    "is_vip",
                    models.BooleanField(default=False, verbose_name="VIP Müşteri mi?"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Müşteri hakkında özel notlar",
                        verbose_name="Notlar",
                    ),
                ),
                (
                    "special_requests",
                    models.TextField(
                        blank=True,
                        help_text="Müşterinin özel istekleri",
                        verbose_name="Özel İstekler",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "last_reservation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son Rezervasyon Tarihi"
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("email", "E-posta"),
                            ("phone", "Telefon"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        default="email",
                        max_length=20,
                        verbose_name="Tercih Edilen İletişim Yöntemi",
                    ),
                ),
                (
                    "allow_marketing",
                    models.BooleanField(
                        default=True, verbose_name="Pazarlama İletişimine İzin Ver"
                    ),
                ),
            ],
            options={
                "verbose_name": "Müşteri",
                "verbose_name_plural": "Müşteriler",
                "ordering": ["-total_spent", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("note", models.TextField(verbose_name="Not")),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("general", "Genel"),
                            ("complaint", "Şikayet"),
                            ("request", "İstek"),
                            ("important", "Önemli"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="Not Tipi",
                    ),
                ),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="Önemli mi?"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_history",
                        to="tenant_core.customer",
                        verbose_name="Müşteri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Müşteri Notu",
                "verbose_name_plural": "Müşteri Notları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerLoyaltyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Pozitif = Ekleme, Negatif = Kullanım",
                        verbose_name="Puan",
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="Sebep"),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        help_text="Hangi modülden geldi (tours, hotels, vb.)",
                        max_length=50,
                        verbose_name="Modül",
                    ),
                ),
                (
                    "reference_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Rezervasyon, işlem vb. ID",
                        null=True,
                        verbose_name="Referans ID",
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="reservation, payment, refund vb.",
                        max_length=50,
                        verbose_name="Referans Tipi",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loyalty_history",
                        to="tenant_core.customer",
                        verbose_name="Müşteri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sadakat Puanı Geçmişi",
                "verbose_name_plural": "Sadakat Puanı Geçmişleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="tenant_core_email_3ea278_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["phone"], name="tenant_core_phone_05122f_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["tc_no"], name="tenant_core_tc_no_7bd99c_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["customer_code"], name="tenant_core_custome_a5e2e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["vip_level", "is_active"], name="tenant_core_vip_lev_9ae22f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["email", "phone", "tc_no"], name="tenant_core_email_d3e24b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("email",),
                name="unique_active_customer_email",
            ),
        ),
    ]
