# Generated by Django 4.2.11 on 2025-11-13 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='gateway_type',
            field=models.CharField(choices=[('iyzico', 'İyzico'), ('paytr', 'PayTR'), ('nestpay', 'NestPay'), ('payu', 'PayU'), ('paymes', 'Paymes'), ('stripe', 'Stripe'), ('garanti', 'Garanti Sanal Pos'), ('isbank', 'İş Bankası Sanal Pos'), ('akbank', 'Akbank Sanal Pos'), ('ziraat', 'Ziraat Bankası Sanal Pos'), ('yapikredi', 'Yapı Kredi Sanal Pos'), ('denizbank', 'Denizbank Sanal Pos'), ('halkbank', 'Halkbank Sanal Pos'), ('qnbfinansbank', 'QNB Finansbank Sanal Pos'), ('teb', 'TEB Sanal Pos'), ('sekerbank', 'Şekerbank Sanal Pos'), ('ingbank', 'ING Bank Sanal Pos'), ('vakifbank', 'Vakıfbank Sanal Pos'), ('fibabanka', 'Fibabanka Sanal Pos'), ('albaraka', 'Albaraka Türk Sanal Pos'), ('kuveytturk', 'Kuveyt Türk Sanal Pos'), ('ziraatkatilim', 'Ziraat Katılım Sanal Pos'), ('vakifkatilim', 'Vakıf Katılım Sanal Pos'), ('other', 'Diğer')], max_length=50, verbose_name='Gateway Tipi'),
        ),
    ]
