# Generated by Django 4.2.11 on 2025-11-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymenttransaction_accounting_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpaymentgateway',
            name='paytr_api_type',
            field=models.CharField(blank=True, choices=[('direct', 'Direkt API'), ('iframe', 'iFrame API')], default='direct', help_text='PayTR için kullanılacak API tipi (Direkt API veya iFrame API)', max_length=20, verbose_name='PayTR API Tipi'),
        ),
    ]
