# Generated by Django 4.2.11 on 2025-11-10 14:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Politika Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Politika Kodu")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        help_text="tours, reservations vb. (Boş = Tüm modüller)",
                        max_length=50,
                        verbose_name="Modül",
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Yüzde İadesi"),
                            ("fixed", "Sabit Tutar İadesi"),
                            ("full", "Tam İade"),
                            ("no_refund", "İade Yok"),
                            ("custom", "Özel Kural"),
                        ],
                        default="percentage",
                        max_length=20,
                        verbose_name="İade Tipi",
                    ),
                ),
                (
                    "refund_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Yüzde iadesi için",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="İade Yüzdesi (%)",
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sabit tutar iadesi için",
                        max_digits=15,
                        verbose_name="Sabit İade Tutarı",
                    ),
                ),
                (
                    "days_before_start",
                    models.IntegerField(
                        blank=True,
                        help_text="Etkinlik/tur başlangıcından kaç gün önce iade yapılabilir",
                        null=True,
                        verbose_name="Başlangıçtan Kaç Gün Önce",
                    ),
                ),
                (
                    "days_after_booking",
                    models.IntegerField(
                        blank=True,
                        help_text="Rezervasyondan kaç gün sonra iade yapılabilir",
                        null=True,
                        verbose_name="Rezervasyondan Kaç Gün Sonra",
                    ),
                ),
                (
                    "max_refund_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Rezervasyondan itibaren maksimum kaç gün içinde iade yapılabilir",
                        null=True,
                        verbose_name="Maksimum İade Süresi (Gün)",
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        choices=[
                            ("original", "Orijinal Ödeme Yöntemi"),
                            ("cash", "Nakit"),
                            ("credit", "Kredi/Hesap Bakiyesi"),
                            ("voucher", "Voucher/Hediye Çeki"),
                        ],
                        default="original",
                        max_length=20,
                        verbose_name="İade Yöntemi",
                    ),
                ),
                (
                    "processing_fee_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="İşlem Ücreti (%)",
                    ),
                ),
                (
                    "processing_fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Sabit İşlem Ücreti",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Varsayılan Politika mı?"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Aynı modül için birden fazla politika varsa öncelik sırası",
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "custom_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Özel iade kuralları JSON formatında",
                        verbose_name="Özel Kurallar",
                    ),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Ayarlar"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
            ],
            options={
                "verbose_name": "İade Politikası",
                "verbose_name_plural": "İade Politikaları",
                "ordering": ["priority", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "request_number",
                    models.CharField(
                        help_text="Otomatik oluşturulur",
                        max_length=50,
                        unique=True,
                        verbose_name="Talep No",
                    ),
                ),
                (
                    "request_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Talep Tarihi"
                    ),
                ),
                (
                    "source_module",
                    models.CharField(
                        help_text="tours, reservations vb.",
                        max_length=50,
                        verbose_name="Kaynak Modül",
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(
                        help_text="Kaynak modülün kayıt ID'si", verbose_name="Kaynak ID"
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="Rezervasyon no, Tur adı vb.",
                        max_length=200,
                        verbose_name="Kaynak Referans",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="Müşteri Adı"),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="Müşteri E-posta"),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Müşteri Telefon"
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Orijinal Tutar"
                    ),
                ),
                (
                    "original_payment_method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Orijinal Ödeme Yöntemi"
                    ),
                ),
                (
                    "original_payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Orijinal Ödeme Tarihi"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="İade Tutarı",
                    ),
                ),
                (
                    "processing_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="İşlem Ücreti",
                    ),
                ),
                (
                    "net_refund",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Net İade Tutarı",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        choices=[
                            ("original", "Orijinal Ödeme Yöntemi"),
                            ("cash", "Nakit"),
                            ("credit", "Kredi/Hesap Bakiyesi"),
                            ("voucher", "Voucher/Hediye Çeki"),
                        ],
                        default="original",
                        max_length=20,
                        verbose_name="İade Yöntemi",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Müşterinin iade talep nedeni",
                        verbose_name="İade Nedeni",
                    ),
                ),
                (
                    "customer_notes",
                    models.TextField(blank=True, verbose_name="Müşteri Notları"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("approved", "Onaylandı"),
                            ("rejected", "Reddedildi"),
                            ("processing", "İşleniyor"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Durum Değişim Tarihi"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Onay Tarihi"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reddedilme nedeni",
                        verbose_name="Red Nedeni",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="İşlem Tarihi"
                    ),
                ),
                (
                    "attachments",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Dosya URL'leri listesi",
                        verbose_name="Ekler",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ek Bilgiler"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_refund_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Onaylayan",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_refund_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_refund_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşleyen",
                    ),
                ),
                (
                    "refund_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refund_requests",
                        to="refunds.refundpolicy",
                        verbose_name="İade Politikası",
                    ),
                ),
            ],
            options={
                "verbose_name": "İade Talebi",
                "verbose_name_plural": "İade Talepleri",
                "ordering": ["-request_date", "-request_number"],
            },
        ),
        migrations.CreateModel(
            name="RefundTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(
                        help_text="Otomatik oluşturulur",
                        max_length=50,
                        unique=True,
                        verbose_name="İşlem No",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="İşlem Tarihi"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="İade Tutarı"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        choices=[
                            ("original", "Orijinal Ödeme Yöntemi"),
                            ("cash", "Nakit"),
                            ("credit", "Kredi/Hesap Bakiyesi"),
                            ("voucher", "Voucher/Hediye Çeki"),
                        ],
                        max_length=20,
                        verbose_name="İade Yöntemi",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="İade ödeme referans numarası",
                        max_length=200,
                        verbose_name="Ödeme Referansı",
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        help_text="İyzico, PayTR vb.",
                        max_length=100,
                        verbose_name="Ödeme Sağlayıcı",
                    ),
                ),
                (
                    "cash_transaction_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Finance modülündeki CashTransaction ID",
                        null=True,
                        verbose_name="Kasa İşlemi ID",
                    ),
                ),
                (
                    "accounting_entry_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Accounting modülündeki JournalEntry ID",
                        null=True,
                        verbose_name="Muhasebe Kaydı ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("processing", "İşleniyor"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Başarısız"),
                            ("cancelled", "İptal Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Durum Değişim Tarihi"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ek Bilgiler"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_refund_transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşleyen",
                    ),
                ),
                (
                    "refund_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="refunds.refundrequest",
                        verbose_name="İade Talebi",
                    ),
                ),
            ],
            options={
                "verbose_name": "İade İşlemi",
                "verbose_name_plural": "İade İşlemleri",
                "ordering": ["-transaction_date", "-transaction_number"],
            },
        ),
        migrations.AddIndex(
            model_name="refundpolicy",
            index=models.Index(
                fields=["module", "is_active"], name="refunds_ref_module_862cb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refundpolicy",
            index=models.Index(
                fields=["is_default"], name="refunds_ref_is_defa_3937bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refundtransaction",
            index=models.Index(
                fields=["refund_request", "status"],
                name="refunds_ref_refund__f79649_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="refundtransaction",
            index=models.Index(
                fields=["transaction_number"], name="refunds_ref_transac_284adc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refundrequest",
            index=models.Index(
                fields=["source_module", "source_id"],
                name="refunds_ref_source__3cb962_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="refundrequest",
            index=models.Index(
                fields=["status", "request_date"], name="refunds_ref_status_35a717_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="refundrequest",
            index=models.Index(
                fields=["request_number"], name="refunds_ref_request_9f0a83_idx"
            ),
        ),
    ]
