# Generated by Django 4.2.11 on 2025-11-10 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenant_core", "0003_customer_customernote_customerloyaltyhistory_and_more"),
        ("refunds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="refundrequest",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refund_requests",
                to="tenant_core.customer",
                verbose_name="Müşteri Profili",
            ),
        ),
    ]
