# Generated by Django 4.2.11 on 2025-11-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotelextraservice'),
        ('refunds', '0002_refundrequest_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundpolicy',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Boş bırakılırsa tüm oteller için genel politika olur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund_policies', to='hotels.hotel', verbose_name='Otel'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Boş bırakılırsa genel iade talebi olur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to='hotels.hotel', verbose_name='Otel'),
        ),
        migrations.AlterField(
            model_name='refundpolicy',
            name='code',
            field=models.SlugField(verbose_name='Politika Kodu'),
        ),
        migrations.AlterUniqueTogether(
            name='refundpolicy',
            unique_together={('hotel', 'code')},
        ),
        migrations.AddIndex(
            model_name='refundpolicy',
            index=models.Index(fields=['hotel', 'module', 'is_active'], name='refunds_ref_hotel_i_00fbee_idx'),
        ),
        migrations.AddIndex(
            model_name='refundpolicy',
            index=models.Index(fields=['hotel', 'is_default'], name='refunds_ref_hotel_i_9fd773_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['hotel', 'status', 'request_date'], name='refunds_ref_hotel_i_958639_idx'),
        ),
    ]
