# Generated by Django 4.2.11 on 2025-11-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='smsgateway',
            new_name='settings_sm_gateway_60b81c_idx',
            old_name='settings_sm_gateway_5a8b8c_idx',
        ),
        migrations.RenameIndex(
            model_name='smsgateway',
            new_name='settings_sm_is_defa_c4414f_idx',
            old_name='settings_sm_is_defa_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='smssentlog',
            new_name='settings_sm_gateway_b86e51_idx',
            old_name='settings_sm_gateway_created_idx',
        ),
        migrations.RenameIndex(
            model_name='smssentlog',
            new_name='settings_sm_status_cc1419_idx',
            old_name='settings_sm_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='smssentlog',
            new_name='settings_sm_recipie_990973_idx',
            old_name='settings_sm_recipie_created_idx',
        ),
        migrations.RenameIndex(
            model_name='smssentlog',
            new_name='settings_sm_related_e25873_idx',
            old_name='settings_sm_related_module_idx',
        ),
        migrations.RenameIndex(
            model_name='smstemplate',
            new_name='settings_sm_code_e7a627_idx',
            old_name='settings_sm_code_789abc_idx',
        ),
        migrations.RenameIndex(
            model_name='smstemplate',
            new_name='settings_sm_categor_eda64c_idx',
            old_name='settings_sm_categor_def456_idx',
        ),
        migrations.RenameIndex(
            model_name='smstemplate',
            new_name='settings_sm_module__5dbf5e_idx',
            old_name='settings_sm_module__ghi789_idx',
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='code',
            field=models.SlugField(help_text='Benzersiz kod: reservation_confirmation', max_length=100, unique=True, verbose_name='Şablon Kodu'),
        ),
    ]
