# Generated by Django 4.2.11 on 2025-11-14 05:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_settings_sm_gateway_5a8b8c_idx_settings_sm_gateway_60b81c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('name', models.CharField(help_text='Örn: Gmail Production, Outlook Ana Hesap', max_length=200, verbose_name='Gateway Adı')),
                ('gateway_type', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook / Office 365'), ('custom', 'Custom SMTP')], max_length=20, verbose_name='Gateway Tipi')),
                ('smtp_credentials', models.JSONField(default=dict, help_text='SMTP host, port, username, password vb.', verbose_name='SMTP Bilgileri')),
                ('smtp_host', models.CharField(blank=True, help_text='Örn: smtp.gmail.com', max_length=500, verbose_name='SMTP Host')),
                ('smtp_port', models.IntegerField(default=587, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='SMTP Port')),
                ('use_tls', models.BooleanField(default=True, verbose_name='TLS Kullan')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='SSL Kullan')),
                ('smtp_timeout', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(300)], verbose_name='SMTP Timeout (saniye)')),
                ('from_email', models.EmailField(help_text='Varsayılan gönderen email adresi', max_length=200, verbose_name='Gönderen Email')),
                ('from_name', models.CharField(blank=True, help_text='Örn: Otel Adı', max_length=200, verbose_name='Gönderen Adı')),
                ('reply_to', models.EmailField(blank=True, help_text='Yanıtların gönderileceği email adresi', max_length=200, verbose_name='Yanıt Adresi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_default', models.BooleanField(default=False, help_text='Sadece bir gateway varsayılan olabilir', verbose_name='Varsayılan Gateway mi?')),
                ('is_test_mode', models.BooleanField(default=False, help_text='Test ortamında çalıştır', verbose_name='Test Modu')),
                ('total_sent', models.IntegerField(default=0, verbose_name='Toplam Gönderilen')),
                ('total_failed', models.IntegerField(default=0, verbose_name='Toplam Başarısız')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Gönderim')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
            ],
            options={
                'verbose_name': 'Email Gateway',
                'verbose_name_plural': "Email Gateway'ler",
                'ordering': ['-is_default', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('name', models.CharField(help_text='Örn: Rezervasyon Onayı, Check-in Hatırlatma', max_length=200, verbose_name='Şablon Adı')),
                ('code', models.SlugField(help_text='Benzersiz kod: reservation_confirmation', max_length=100, unique=True, verbose_name='Şablon Kodu')),
                ('category', models.CharField(choices=[('reservation', 'Rezervasyon'), ('checkin', 'Check-in'), ('checkout', 'Check-out'), ('payment', 'Ödeme'), ('notification', 'Bildirim'), ('marketing', 'Pazarlama'), ('other', 'Diğer')], default='other', max_length=50, verbose_name='Kategori')),
                ('subject', models.CharField(help_text='Değişkenler: {{guest_name}}, {{check_in_date}} vb.', max_length=200, verbose_name='Email Konusu')),
                ('template_html', models.TextField(blank=True, help_text='HTML formatında email şablonu', verbose_name='HTML Şablon')),
                ('template_text', models.TextField(blank=True, help_text='Plain text alternatifi (HTML yoksa kullanılır)', verbose_name='Metin Şablonu')),
                ('available_variables', models.JSONField(default=dict, help_text='Şablonda kullanılabilecek değişkenler ve açıklamaları', verbose_name='Kullanılabilir Değişkenler')),
                ('module_usage', models.CharField(blank=True, help_text='Örn: reception, ferry_tickets, tours', max_length=100, verbose_name='Kullanıldığı Modül')),
                ('description', models.TextField(blank=True, help_text='Şablonun ne zaman ve nasıl kullanılacağı', verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_system_template', models.BooleanField(default=False, help_text='Sistem şablonları silinemez', verbose_name='Sistem Şablonu mu?')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Kullanım Sayısı')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Kullanım')),
            ],
            options={
                'verbose_name': 'Email Şablonu',
                'verbose_name_plural': 'Email Şablonları',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['code'], name='settings_em_code_2441a4_idx'), models.Index(fields=['category', 'is_active'], name='settings_em_categor_288112_idx'), models.Index(fields=['module_usage'], name='settings_em_module__be3f4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailSentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('recipient_email', models.EmailField(max_length=200, verbose_name='Alıcı Email')),
                ('recipient_name', models.CharField(blank=True, max_length=200, verbose_name='Alıcı Adı')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('message_html', models.TextField(blank=True, verbose_name='HTML İçerik')),
                ('message_text', models.TextField(blank=True, verbose_name='Metin İçerik')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('sent', 'Gönderildi'), ('delivered', 'Teslim Edildi'), ('failed', 'Başarısız'), ('bounced', 'Geri Döndü'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('smtp_response', models.JSONField(blank=True, default=dict, verbose_name='SMTP Yanıtı')),
                ('message_id', models.CharField(blank=True, max_length=200, verbose_name='Email Mesaj ID')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderim Zamanı')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Zamanı')),
                ('related_module', models.CharField(blank=True, max_length=100, verbose_name='İlişkili Modül')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='İlişkili Kayıt ID')),
                ('related_object_type', models.CharField(blank=True, max_length=100, verbose_name='İlişkili Kayıt Tipi')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Şablon render için kullanılan değişkenler', verbose_name='Context Verisi')),
                ('gateway', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_logs', to='settings.emailgateway', verbose_name='Gateway')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_logs', to='settings.emailtemplate', verbose_name='Şablon')),
            ],
            options={
                'verbose_name': 'Email Gönderim Logu',
                'verbose_name_plural': 'Email Gönderim Logları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailgateway',
            index=models.Index(fields=['gateway_type', 'is_active'], name='settings_em_gateway_d4771a_idx'),
        ),
        migrations.AddIndex(
            model_name='emailgateway',
            index=models.Index(fields=['is_default'], name='settings_em_is_defa_4c766a_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsentlog',
            index=models.Index(fields=['gateway', '-created_at'], name='settings_em_gateway_675649_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsentlog',
            index=models.Index(fields=['status', '-created_at'], name='settings_em_status_950d26_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsentlog',
            index=models.Index(fields=['recipient_email', '-created_at'], name='settings_em_recipie_515c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='emailsentlog',
            index=models.Index(fields=['related_module', 'related_object_id'], name='settings_em_related_fb0ec2_idx'),
        ),
    ]
