"""
Varsayılan ödeme gateway'lerini oluştur
"""
from django.core.management.base import BaseCommand
from apps.payments.models import PaymentGateway


class Command(BaseCommand):
    help = 'Varsayılan ödeme gateway\'lerini oluştur'

    def handle(self, *args, **options):
        gateways = [
            # Gateway'ler
            {
                'name': 'İyzico',
                'code': 'iyzico',
                'gateway_type': 'iyzico',
                'description': 'İyzico ödeme gateway entegrasyonu - Türkiye\'nin önde gelen ödeme çözümü',
                'api_url': 'https://api.iyzipay.com',
                'test_api_url': 'https://sandbox-api.iyzipay.com',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 1,
            },
            {
                'name': 'PayTR',
                'code': 'paytr',
                'gateway_type': 'paytr',
                'description': 'PayTR ödeme gateway entegrasyonu - Hızlı ve güvenli ödeme',
                'api_url': 'https://www.paytr.com/odeme/api/get-token',
                'test_api_url': 'https://www.paytr.com/odeme/api/get-token',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 2,
            },
            {
                'name': 'PayU',
                'code': 'payu',
                'gateway_type': 'payu',
                'description': 'PayU ödeme gateway entegrasyonu',
                'api_url': 'https://secure.payu.com.tr',
                'test_api_url': 'https://secure.payu.com.tr',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 3,
            },
            # Türk Bankaları - Sanal Pos
            {
                'name': 'Garanti Sanal Pos',
                'code': 'garanti',
                'gateway_type': 'garanti',
                'description': 'Garanti Bankası sanal pos entegrasyonu',
                'api_url': 'https://sanalposprov.garanti.com.tr',
                'test_api_url': 'https://sanalposprovtest.garanti.com.tr',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 10,
            },
            {
                'name': 'İş Bankası Sanal Pos',
                'code': 'isbank',
                'gateway_type': 'isbank',
                'description': 'İş Bankası sanal pos entegrasyonu (NestPay)',
                'api_url': 'https://sanalpos.isbank.com.tr',
                'test_api_url': 'https://sanalpos.isbank.com.tr',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 11,
            },
            {
                'name': 'Akbank Sanal Pos',
                'code': 'akbank',
                'gateway_type': 'akbank',
                'description': 'Akbank sanal pos entegrasyonu (NestPay)',
                'api_url': 'https://www.sanalakpos.com',
                'test_api_url': 'https://www.sanalakpos.com',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 12,
            },
            {
                'name': 'Ziraat Bankası Sanal Pos',
                'code': 'ziraat',
                'gateway_type': 'ziraat',
                'description': 'Ziraat Bankası sanal pos entegrasyonu (NestPay)',
                'api_url': 'https://sanalpos.ziraatbank.com.tr',
                'test_api_url': 'https://sanalpos.ziraatbank.com.tr',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 13,
            },
            {
                'name': 'Yapı Kredi Sanal Pos',
                'code': 'yapikredi',
                'gateway_type': 'yapikredi',
                'description': 'Yapı Kredi Bankası sanal pos entegrasyonu (NestPay)',
                'api_url': 'https://posnet.yapikredi.com.tr',
                'test_api_url': 'https://posnet.yapikredi.com.tr',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 14,
            },
            {
                'name': 'Denizbank Sanal Pos',
                'code': 'denizbank',
                'gateway_type': 'denizbank',
                'description': 'Denizbank sanal pos entegrasyonu',
                'api_url': 'https://sanalpos.denizbank.com',
                'test_api_url': 'https://sanalpos.denizbank.com',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 15,
            },
            {
                'name': 'Halkbank Sanal Pos',
                'code': 'halkbank',
                'gateway_type': 'halkbank',
                'description': 'Halkbank sanal pos entegrasyonu (NestPay)',
                'api_url': 'https://sanalpos.halkbank.com.tr',
                'test_api_url': 'https://sanalpos.halkbank.com.tr',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 16,
            },
            {
                'name': 'QNB Finansbank Sanal Pos',
                'code': 'qnbfinansbank',
                'gateway_type': 'qnbfinansbank',
                'description': 'QNB Finansbank sanal pos entegrasyonu (NestPay)',
                'api_url': 'https://sanalpos.qnbfinansbank.com',
                'test_api_url': 'https://sanalpos.qnbfinansbank.com',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 17,
            },
            {
                'name': 'TEB Sanal Pos',
                'code': 'teb',
                'gateway_type': 'teb',
                'description': 'TEB sanal pos entegrasyonu (NestPay)',
                'api_url': 'https://sanalpos.teb.com.tr',
                'test_api_url': 'https://sanalpos.teb.com.tr',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 18,
            },
            {
                'name': 'Şekerbank Sanal Pos',
                'code': 'sekerbank',
                'gateway_type': 'sekerbank',
                'description': 'Şekerbank sanal pos entegrasyonu (NestPay)',
                'api_url': 'https://sanalpos.sekerbank.com.tr',
                'test_api_url': 'https://sanalpos.sekerbank.com.tr',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 19,
            },
            {
                'name': 'ING Bank Sanal Pos',
                'code': 'ingbank',
                'gateway_type': 'ingbank',
                'description': 'ING Bank sanal pos entegrasyonu (NestPay)',
                'api_url': 'https://sanalpos.ingbank.com.tr',
                'test_api_url': 'https://sanalpos.ingbank.com.tr',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 20,
            },
            {
                'name': 'Vakıfbank Sanal Pos',
                'code': 'vakifbank',
                'gateway_type': 'vakifbank',
                'description': 'Vakıfbank sanal pos entegrasyonu (NestPay)',
                'api_url': 'https://sanalpos.vakifbank.com.tr',
                'test_api_url': 'https://sanalpos.vakifbank.com.tr',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 21,
            },
            {
                'name': 'Fibabanka Sanal Pos',
                'code': 'fibabanka',
                'gateway_type': 'fibabanka',
                'description': 'Fibabanka sanal pos entegrasyonu (NestPay)',
                'api_url': 'https://sanalpos.fibabanka.com.tr',
                'test_api_url': 'https://sanalpos.fibabanka.com.tr',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 22,
            },
            {
                'name': 'Albaraka Türk Sanal Pos',
                'code': 'albaraka',
                'gateway_type': 'albaraka',
                'description': 'Albaraka Türk sanal pos entegrasyonu (NestPay)',
                'api_url': 'https://sanalpos.albaraka.com.tr',
                'test_api_url': 'https://sanalpos.albaraka.com.tr',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 23,
            },
            {
                'name': 'Kuveyt Türk Sanal Pos',
                'code': 'kuveytturk',
                'gateway_type': 'kuveytturk',
                'description': 'Kuveyt Türk sanal pos entegrasyonu (NestPay)',
                'api_url': 'https://sanalpos.kuveytturk.com.tr',
                'test_api_url': 'https://sanalpos.kuveytturk.com.tr',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 24,
            },
            {
                'name': 'Ziraat Katılım Sanal Pos',
                'code': 'ziraatkatilim',
                'gateway_type': 'ziraatkatilim',
                'description': 'Ziraat Katılım Bankası sanal pos entegrasyonu (NestPay)',
                'api_url': 'https://sanalpos.ziraatkatilim.com.tr',
                'test_api_url': 'https://sanalpos.ziraatkatilim.com.tr',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 25,
            },
            {
                'name': 'Vakıf Katılım Sanal Pos',
                'code': 'vakifkatilim',
                'gateway_type': 'vakifkatilim',
                'description': 'Vakıf Katılım Bankası sanal pos entegrasyonu (NestPay)',
                'api_url': 'https://sanalpos.vakifkatilim.com.tr',
                'test_api_url': 'https://sanalpos.vakifkatilim.com.tr',
                'supports_3d_secure': True,
                'supports_installment': True,
                'supports_refund': True,
                'supports_recurring': False,
                'is_active': True,
                'sort_order': 26,
            },
        ]
        
        created_count = 0
        for gateway_data in gateways:
            gateway, created = PaymentGateway.objects.get_or_create(
                code=gateway_data['code'],
                defaults=gateway_data
            )
            if created:
                created_count += 1
                self.stdout.write(
                    self.style.SUCCESS(f'[OK] {gateway.name} olusturuldu')
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f'[SKIP] {gateway.name} zaten mevcut')
                )
        
        self.stdout.write(
            self.style.SUCCESS(f'\n{created_count} gateway oluşturuldu')
        )

