# Generated by Django 4.2.11 on 2025-11-14 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ferry_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferryapisync',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferry_api_syncs', to=settings.AUTH_USER_MODEL, verbose_name='Başlatan Kullanıcı'),
        ),
        migrations.AddField(
            model_name='ferryapisync',
            name='sync_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Senkronizasyon Verileri'),
        ),
        migrations.AlterField(
            model_name='ferryapisync',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='ferryapisync',
            name='status',
            field=models.CharField(choices=[('running', 'Çalışıyor'), ('completed', 'Tamamlandı'), ('success', 'Başarılı'), ('failed', 'Başarısız'), ('partial', 'Kısmi Başarılı')], default='running', max_length=20, verbose_name='Durum'),
        ),
    ]
