# Generated by Django 4.2.11 on 2025-11-14 03:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_core', '0003_customer_customernote_customerloyaltyhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('backup_type', models.CharField(choices=[('manual', 'Manuel'), ('automatic', 'Otomatik')], default='manual', max_length=20, verbose_name='Yedekleme Tipi')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Durum')),
                ('file_name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Dosya Adı')),
                ('file_path', models.CharField(max_length=500, verbose_name='Dosya Yolu')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Dosya Boyutu (bytes)')),
                ('schema_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Schema Adı')),
                ('database_name', models.CharField(max_length=100, verbose_name='Veritabanı Adı')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç Zamanı')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Zamanı')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_started', to='tenant_core.tenantuser', verbose_name='Başlatan Kullanıcı')),
            ],
            options={
                'verbose_name': 'Veritabanı Yedeği',
                'verbose_name_plural': 'Veritabanı Yedekleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_name'], name='backup_data_file_na_c6e802_idx'), models.Index(fields=['status'], name='backup_data_status_062775_idx'), models.Index(fields=['backup_type'], name='backup_data_backup__639aab_idx'), models.Index(fields=['created_at'], name='backup_data_created_0ba118_idx')],
            },
        ),
    ]
