# Generated by Django 4.2.11 on 2025-11-09 14:59

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("packages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="İşletme Adı")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "owner_name",
                    models.CharField(max_length=100, verbose_name="Sahip Adı"),
                ),
                (
                    "owner_email",
                    models.EmailField(max_length=254, verbose_name="Sahip E-posta"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adres")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Şehir"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Türkiye", max_length=100, verbose_name="Ülke"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_trial",
                    models.BooleanField(default=True, verbose_name="Deneme mi?"),
                ),
                (
                    "trial_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Deneme Bitiş Tarihi"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(blank=True, default=dict, verbose_name="Ayarlar"),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenants",
                        to="packages.package",
                        verbose_name="Paket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Üye (Tenant)",
                "verbose_name_plural": "Üyeler (Tenants)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "domain_type",
                    models.CharField(
                        choices=[
                            ("primary", "Ana Domain"),
                            ("custom", "Özel Domain"),
                            ("subdomain", "Alt Domain"),
                        ],
                        default="subdomain",
                        max_length=20,
                        verbose_name="Domain Tipi",
                    ),
                ),
                (
                    "ssl_enabled",
                    models.BooleanField(default=False, verbose_name="SSL Aktif mi?"),
                ),
                (
                    "ssl_certificate",
                    models.TextField(blank=True, verbose_name="SSL Sertifikası"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                        verbose_name="Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domainler",
                "ordering": ["domain"],
            },
        ),
    ]
