# Generated by Django 4.2.11 on 2025-11-12 02:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0004_hotelextraservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalServiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('auto_assign_requests', models.BooleanField(default=False, verbose_name='Otomatik Talep Atama')),
                ('default_priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], default='normal', max_length=20, verbose_name='Varsayılan Öncelik')),
                ('maintenance_reminder_days', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Bakım Hatırlatma Günü')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical_service_settings', to='hotels.hotel', verbose_name='Otel')),
            ],
            options={
                'verbose_name': 'Teknik Servis Ayarları',
                'verbose_name_plural': 'Teknik Servis Ayarları',
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('request_type', models.CharField(choices=[('plumbing', 'Tesisat'), ('electrical', 'Elektrik'), ('hvac', 'Isıtma/Soğutma'), ('furniture', 'Mobilya'), ('appliance', 'Cihaz'), ('paint', 'Boya'), ('other', 'Diğer')], default='other', max_length=50, verbose_name='Talep Tipi')),
                ('priority', models.CharField(choices=[('low', 'Düşük'), ('normal', 'Normal'), ('high', 'Yüksek'), ('urgent', 'Acil')], db_index=True, default='normal', max_length=20, verbose_name='Öncelik')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Bildirim Tarihi')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('assigned', 'Atandı'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Atanma Tarihi')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('completion_notes', models.TextField(blank=True, verbose_name='Tamamlanma Notları')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tahmini Maliyet')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gerçek Maliyet')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Atanan Teknisyen')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='hotels.hotel', verbose_name='Otel')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Bildiren')),
                ('room_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='hotels.roomnumber', verbose_name='Oda Numarası')),
            ],
            options={
                'verbose_name': 'Bakım Talebi',
                'verbose_name_plural': 'Bakım Talepleri',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('equipment_name', models.CharField(max_length=200, verbose_name='Ekipman Adı')),
                ('equipment_type', models.CharField(choices=[('hvac', 'Isıtma/Soğutma'), ('plumbing', 'Tesisat'), ('electrical', 'Elektrik'), ('appliance', 'Cihaz'), ('furniture', 'Mobilya'), ('other', 'Diğer')], default='other', max_length=50, verbose_name='Ekipman Tipi')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Önleyici'), ('corrective', 'Düzeltici'), ('emergency', 'Acil')], default='corrective', max_length=50, verbose_name='Bakım Tipi')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bakım Tarihi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('parts_used', models.TextField(blank=True, verbose_name='Kullanılan Parçalar')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maliyet')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Sonraki Bakım Tarihi')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='hotels.hotel', verbose_name='Otel')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Yapan Teknisyen')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='technical_service.maintenancerequest', verbose_name='Bakım Talebi')),
            ],
            options={
                'verbose_name': 'Bakım Kaydı',
                'verbose_name_plural': 'Bakım Kayıtları',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('name', models.CharField(max_length=200, verbose_name='Ekipman Adı')),
                ('equipment_type', models.CharField(choices=[('hvac', 'Isıtma/Soğutma'), ('plumbing', 'Tesisat'), ('electrical', 'Elektrik'), ('appliance', 'Cihaz'), ('furniture', 'Mobilya'), ('other', 'Diğer')], default='other', max_length=50, verbose_name='Ekipman Tipi')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marka')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Seri Numarası')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Satın Alma Tarihi')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Garanti Bitiş Tarihi')),
                ('status', models.CharField(choices=[('operational', 'Çalışır Durumda'), ('maintenance', 'Bakımda'), ('broken', 'Arızalı'), ('retired', 'Emekli'), ('spare', 'Yedek')], db_index=True, default='operational', max_length=20, verbose_name='Durum')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Son Bakım Tarihi')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Sonraki Bakım Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='hotels.hotel', verbose_name='Otel')),
                ('room_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='hotels.roomnumber', verbose_name='Oda Numarası')),
            ],
            options={
                'verbose_name': 'Ekipman',
                'verbose_name_plural': 'Ekipmanlar',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['hotel', 'status', 'priority'], name='technical_s_hotel_i_fe21e5_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['hotel', 'status'], name='technical_s_hotel_i_dd1b1b_idx'),
        ),
    ]
