# Generated by Django 4.2.11 on 2025-11-10 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantAICredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "tenant_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Tenant ID (loglama için)",
                        null=True,
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "tenant_name",
                    models.CharField(
                        blank=True,
                        help_text="Tenant adı (loglama için)",
                        max_length=200,
                        verbose_name="Tenant Adı",
                    ),
                ),
                (
                    "total_credits",
                    models.IntegerField(
                        default=0,
                        help_text="Toplam kullanılabilir kredi",
                        verbose_name="Toplam Kredi",
                    ),
                ),
                (
                    "used_credits",
                    models.IntegerField(
                        default=0,
                        help_text="Kullanılan kredi miktarı",
                        verbose_name="Kullanılan Kredi",
                    ),
                ),
                (
                    "last_renewal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son Yenileme Tarihi"
                    ),
                ),
                (
                    "next_renewal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Sonraki Yenileme Tarihi"
                    ),
                ),
                (
                    "renewal_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Aylık"),
                            ("yearly", "Yıllık"),
                            ("manual", "Manuel"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Yenileme Tipi",
                    ),
                ),
                (
                    "manual_credits",
                    models.IntegerField(
                        default=0,
                        help_text="Paket dışında manuel olarak eklenen kredi",
                        verbose_name="Manuel Eklenen Kredi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant AI Kredi",
                "verbose_name_plural": "Tenant AI Kredileri",
            },
        ),
        migrations.CreateModel(
            name="TenantAIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "tenant_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Tenant ID"
                    ),
                ),
                (
                    "tenant_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Tenant Adı"
                    ),
                ),
                (
                    "ai_provider_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="AI Sağlayıcı Adı"
                    ),
                ),
                (
                    "ai_model_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="AI Model Adı"
                    ),
                ),
                (
                    "ai_provider_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="AI Sağlayıcı Kodu"
                    ),
                ),
                (
                    "ai_model_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="AI Model Kodu"
                    ),
                ),
                (
                    "usage_type",
                    models.CharField(
                        choices=[
                            ("tour_program", "Tur Programı Oluşturma"),
                            ("tour_description", "Tur Açıklaması Oluşturma"),
                            ("form_fill", "Form Doldurma"),
                            ("website_generate", "Web Sitesi Oluşturma"),
                            ("other", "Diğer"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="Kullanım Tipi",
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        blank=True,
                        help_text="Kullanıcının gönderdiği prompt",
                        verbose_name="Prompt",
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, help_text="AI'dan gelen yanıt", verbose_name="Yanıt"
                    ),
                ),
                (
                    "credit_used",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        max_digits=10,
                        verbose_name="Kullanılan Kredi",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Başarılı"),
                            ("failed", "Başarısız"),
                            ("error", "Hata"),
                        ],
                        default="success",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Token sayısı, süre vb. ek bilgiler",
                        verbose_name="Ek Bilgiler",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Kullanım Logu",
                "verbose_name_plural": "AI Kullanım Logları",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="ai_tenant_t_tenant__19aa9f_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "usage_type"],
                        name="ai_tenant_t_tenant__3b32cf_idx",
                    ),
                ],
            },
        ),
    ]
