# Generated by Django 4.2.11 on 2025-11-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotelextraservice'),
        ('accounting', '0002_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Boş bırakılırsa tüm oteller için genel hesap olur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='hotels.hotel', verbose_name='Otel'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Boş bırakılırsa genel fatura olur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='hotels.hotel', verbose_name='Otel'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Boş bırakılırsa genel yevmiye kaydı olur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='hotels.hotel', verbose_name='Otel'),
        ),
        migrations.AddField(
            model_name='payment',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Boş bırakılırsa genel ödeme olur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='hotels.hotel', verbose_name='Otel'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(help_text='Hesap planı kodu (örn: 100, 120, 600)', max_length=20, verbose_name='Hesap Kodu'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('hotel', 'code')},
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['hotel', 'account_type'], name='accounting__hotel_i_be214d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['hotel', 'invoice_date'], name='accounting__hotel_i_c58b89_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['hotel', 'entry_date'], name='accounting__hotel_i_ebab03_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['hotel', 'payment_date'], name='accounting__hotel_i_a28893_idx'),
        ),
    ]
