# Generated by Django 4.2.11 on 2025-11-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('name', models.CharField(max_length=200, verbose_name='Kanal Adı')),
                ('code', models.SlugField(unique=True, verbose_name='Kanal Kodu')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('api_key', models.CharField(blank=True, max_length=200, verbose_name='API Key')),
                ('api_secret', models.CharField(blank=True, max_length=200, verbose_name='API Secret')),
                ('api_url', models.URLField(blank=True, verbose_name='API URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Kanal',
                'verbose_name_plural': 'Kanallar',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
