# Generated by Django 4.2.11 on 2025-11-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotelextraservice'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashflow',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cashaccount',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Boş bırakılırsa tüm oteller için genel kasa hesabı olur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_accounts', to='hotels.hotel', verbose_name='Otel'),
        ),
        migrations.AddField(
            model_name='cashflow',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Boş bırakılırsa genel nakit akışı olur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='hotels.hotel', verbose_name='Otel'),
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Boş bırakılırsa genel kasa işlemi olur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to='hotels.hotel', verbose_name='Otel'),
        ),
        migrations.AlterField(
            model_name='cashaccount',
            name='code',
            field=models.SlugField(verbose_name='Hesap Kodu'),
        ),
        migrations.AlterUniqueTogether(
            name='cashaccount',
            unique_together={('hotel', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='cashflow',
            unique_together={('account', 'hotel', 'period_type', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='cashaccount',
            index=models.Index(fields=['hotel', 'is_active'], name='finance_cas_hotel_i_a55a53_idx'),
        ),
        migrations.AddIndex(
            model_name='cashaccount',
            index=models.Index(fields=['hotel', 'is_default'], name='finance_cas_hotel_i_e97d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflow',
            index=models.Index(fields=['hotel', 'period_type', '-period_start'], name='finance_cas_hotel_i_bf04f4_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['hotel', '-payment_date'], name='finance_cas_hotel_i_e7d6f8_idx'),
        ),
    ]
