# Generated by Django 4.2.11 on 2025-11-12 22:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant_core', '0003_customer_customernote_customerloyaltyhistory_and_more'),
        ('hotels', '0004_hotelextraservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('reservation_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Rezervasyon Kodu')),
                ('check_in_date', models.DateField(db_index=True, verbose_name='Check-in Tarihi')),
                ('check_out_date', models.DateField(db_index=True, verbose_name='Check-out Tarihi')),
                ('check_in_time', models.TimeField(default='14:00', verbose_name='Check-in Saati')),
                ('check_out_time', models.TimeField(default='12:00', verbose_name='Check-out Saati')),
                ('adult_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Yetişkin Sayısı')),
                ('child_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Çocuk Sayısı')),
                ('child_ages', models.JSONField(blank=True, default=list, help_text='Örn: [5, 8]', verbose_name='Çocuk Yaşları')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('confirmed', 'Onaylandı'), ('checked_in', 'Check-In Yapıldı'), ('checked_out', 'Check-Out Yapıldı'), ('cancelled', 'İptal Edildi'), ('no_show', 'Gelmedi')], db_index=True, default='pending', max_length=20, verbose_name='Durum')),
                ('source', models.CharField(choices=[('direct', 'Direkt'), ('online', 'Online'), ('phone', 'Telefon'), ('email', 'E-posta'), ('walk_in', 'Walk-In'), ('agency', 'Acente'), ('corporate', 'Kurumsal')], db_index=True, default='direct', max_length=20, verbose_name='Kaynak')),
                ('room_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Oda Fiyatı')),
                ('total_nights', models.IntegerField(default=1, verbose_name='Toplam Gece')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Toplam Tutar')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='İndirim Tutarı')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vergi Tutarı')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ödenen Tutar')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('special_requests', models.TextField(blank=True, verbose_name='Özel İstekler')),
                ('internal_notes', models.TextField(blank=True, help_text='Personel için notlar', verbose_name='İç Notlar')),
                ('is_checked_in', models.BooleanField(default=False, verbose_name='Check-In Yapıldı mı?')),
                ('is_checked_out', models.BooleanField(default=False, verbose_name='Check-Out Yapıldı mı?')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Check-In Tarihi')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Check-Out Tarihi')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='İptal Tarihi')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='İptal Nedeni')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tenant_core.customer', verbose_name='Müşteri')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotels.hotel', verbose_name='Otel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotels.room', verbose_name='Oda Tipi')),
                ('room_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='hotels.roomnumber', verbose_name='Oda Numarası')),
            ],
            options={
                'verbose_name': 'Rezervasyon',
                'verbose_name_plural': 'Rezervasyonlar',
                'ordering': ['-check_in_date', '-created_at'],
                'indexes': [models.Index(fields=['hotel', 'status', 'check_in_date'], name='reception_r_hotel_i_a60379_idx'), models.Index(fields=['customer', 'status'], name='reception_r_custome_f88057_idx'), models.Index(fields=['reservation_code'], name='reception_r_reserva_703f43_idx')],
            },
        ),
    ]
