# Generated by Django 4.2.11 on 2025-11-11 23:02

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tours", "0009_alter_tourreservation_customer"),
        ("tenant_core", "0003_customer_customernote_customerloyaltyhistory_and_more"),
        ("hotels", "0004_hotelextraservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "reservation_code",
                    models.CharField(
                        db_index=True,
                        help_text="Otomatik oluşturulur (örn: RES-2025-001)",
                        max_length=50,
                        unique=True,
                        verbose_name="Rezervasyon Kodu",
                    ),
                ),
                (
                    "customer_first_name",
                    models.CharField(max_length=100, verbose_name="Müşteri Adı"),
                ),
                (
                    "customer_last_name",
                    models.CharField(max_length=100, verbose_name="Müşteri Soyadı"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="E-posta"
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Telefon"
                    ),
                ),
                (
                    "customer_tc_no",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=11,
                        verbose_name="TC Kimlik No",
                    ),
                ),
                (
                    "customer_address",
                    models.TextField(blank=True, verbose_name="Adres"),
                ),
                (
                    "child_count",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Çocuk Sayısı",
                    ),
                ),
                (
                    "child_ages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[5, 8, 12] - Her çocuk için yaş bilgisi (0'dan büyük olmalı)",
                        verbose_name="Çocuk Yaşları",
                    ),
                ),
                (
                    "check_in_date",
                    models.DateField(db_index=True, verbose_name="Giriş Tarihi"),
                ),
                (
                    "check_out_date",
                    models.DateField(db_index=True, verbose_name="Çıkış Tarihi"),
                ),
                (
                    "check_in_time",
                    models.TimeField(blank=True, null=True, verbose_name="Giriş Saati"),
                ),
                (
                    "check_out_time",
                    models.TimeField(blank=True, null=True, verbose_name="Çıkış Saati"),
                ),
                (
                    "nights",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Gece Sayısı",
                    ),
                ),
                (
                    "adult_count",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Yetişkin Sayısı",
                    ),
                ),
                (
                    "total_people",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Toplam Kişi",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Temel Fiyat"
                    ),
                ),
                (
                    "adult_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Yetişkin Fiyatı",
                    ),
                ),
                (
                    "child_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Çocuk Fiyatı",
                    ),
                ),
                (
                    "extra_services_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ekstra Hizmetler Toplam",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="İndirim Tutarı",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Toplam Tutar"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="TRY", max_length=3, verbose_name="Para Birimi"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("reception", "Resepsiyon"),
                            ("sales", "Satış"),
                            ("call_center", "Call Center"),
                            ("agency", "Acente"),
                            ("web", "Web"),
                            ("channel", "Kanal"),
                        ],
                        db_index=True,
                        default="reception",
                        max_length=20,
                        verbose_name="Kaynak",
                    ),
                ),
                (
                    "channel_id",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Kanal ID"
                    ),
                ),
                (
                    "channel_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kanal Adı"
                    ),
                ),
                (
                    "is_web_booking",
                    models.BooleanField(
                        default=False, verbose_name="Web Rezervasyonu mu?"
                    ),
                ),
                (
                    "web_booking_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Web Rezervasyon Referansı",
                    ),
                ),
                (
                    "is_complimentary",
                    models.BooleanField(
                        default=False, verbose_name="Comp Rezervasyon mu?"
                    ),
                ),
                (
                    "complimentary_reason",
                    models.TextField(blank=True, verbose_name="Comp Nedeni"),
                ),
                (
                    "complimentary_approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Comp Onay Tarihi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("confirmed", "Onaylandı"),
                            ("checked_in", "Check-in Yapıldı"),
                            ("checked_out", "Check-out Yapıldı"),
                            ("cancelled", "İptal Edildi"),
                            ("no_show", "Gelmedi (No-Show)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "checked_in_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Check-in Tarihi"
                    ),
                ),
                (
                    "checked_out_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Check-out Tarihi"
                    ),
                ),
                (
                    "is_early_checkout",
                    models.BooleanField(default=False, verbose_name="Erken Çıkış mı?"),
                ),
                (
                    "early_checkout_reason",
                    models.TextField(blank=True, verbose_name="Erken Çıkış Nedeni"),
                ),
                (
                    "early_checkout_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Erken Çıkış Ücreti",
                    ),
                ),
                (
                    "is_late_checkout",
                    models.BooleanField(default=False, verbose_name="Geç Çıkış mı?"),
                ),
                (
                    "late_checkout_reason",
                    models.TextField(blank=True, verbose_name="Geç Çıkış Nedeni"),
                ),
                (
                    "late_checkout_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Geç Çıkış Ücreti",
                    ),
                ),
                (
                    "is_guaranteed",
                    models.BooleanField(
                        default=False, verbose_name="Ödeme Garantili mi?"
                    ),
                ),
                (
                    "guarantee_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("credit_card", "Kredi Kartı"),
                            ("deposit", "Depozito"),
                            ("voucher", "Voucher"),
                            ("other", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="Garanti Tipi",
                    ),
                ),
                (
                    "advance_payment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ön Ödeme",
                    ),
                ),
                (
                    "special_requests",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"extra_bed": true, "baby_cot": true, "accompaniateur": false}',
                        verbose_name="Özel İstekler",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        help_text="Sadece personel görebilir",
                        verbose_name="İç Notlar",
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Arşivlenme Tarihi"
                    ),
                ),
                (
                    "archive_reason",
                    models.TextField(blank=True, verbose_name="Arşivleme Nedeni"),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hotel_reservations",
                        to="tours.touragency",
                        verbose_name="Acente",
                    ),
                ),
                (
                    "archived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="archived_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Arşivleyen",
                    ),
                ),
                (
                    "board_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="hotels.boardtype",
                        verbose_name="Pansiyon Tipi",
                    ),
                ),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_in_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Check-in Yapan",
                    ),
                ),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_out_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Check-out Yapan",
                    ),
                ),
                (
                    "complimentary_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_comps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Comp Onaylayan",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan Kullanıcı",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hotel_reservations",
                        to="tenant_core.customer",
                        verbose_name="Müşteri Profili",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="hotels.hotel",
                        verbose_name="Otel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="hotels.room",
                        verbose_name="Oda Tipi",
                    ),
                ),
                (
                    "room_number",
                    models.ForeignKey(
                        blank=True,
                        help_text="Check-in sırasında atanır",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="hotels.roomnumber",
                        verbose_name="Oda Numarası",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezervasyon",
                "verbose_name_plural": "Rezervasyonlar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoomChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Neden")),
                (
                    "price_difference",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Yeni oda fiyatı - Eski oda fiyatı",
                        max_digits=10,
                        null=True,
                        verbose_name="Fiyat Farkı",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Değiştiren",
                    ),
                ),
                (
                    "new_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="room_changes_to",
                        to="hotels.room",
                        verbose_name="Yeni Oda",
                    ),
                ),
                (
                    "new_room_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_changes_to",
                        to="hotels.roomnumber",
                        verbose_name="Yeni Oda Numarası",
                    ),
                ),
                (
                    "old_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="room_changes_from",
                        to="hotels.room",
                        verbose_name="Eski Oda",
                    ),
                ),
                (
                    "old_room_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_changes_from",
                        to="hotels.roomnumber",
                        verbose_name="Eski Oda Numarası",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_changes",
                        to="reception.reservation",
                        verbose_name="Rezervasyon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Oda Değişikliği",
                "verbose_name_plural": "Oda Değişiklikleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceptionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "default_checkin_time",
                    models.TimeField(
                        default="14:00", verbose_name="Varsayılan Check-in Saati"
                    ),
                ),
                (
                    "default_checkout_time",
                    models.TimeField(
                        default="12:00", verbose_name="Varsayılan Check-out Saati"
                    ),
                ),
                (
                    "early_checkin_allowed",
                    models.BooleanField(
                        default=True, verbose_name="Erken Check-in İzni"
                    ),
                ),
                (
                    "early_checkin_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Erken Check-in Ücreti",
                    ),
                ),
                (
                    "late_checkout_allowed",
                    models.BooleanField(
                        default=True, verbose_name="Geç Check-out İzni"
                    ),
                ),
                (
                    "late_checkout_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Geç Check-out Ücreti",
                    ),
                ),
                (
                    "late_checkout_hour_limit",
                    models.IntegerField(
                        default=12,
                        help_text="Saat 12'den sonra geç çıkış sayılır",
                        verbose_name="Geç Check-out Saat Limiti",
                    ),
                ),
                (
                    "early_checkout_allowed",
                    models.BooleanField(
                        default=True, verbose_name="Erken Check-out İzni"
                    ),
                ),
                (
                    "early_checkout_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Erken Check-out Ücreti",
                    ),
                ),
                (
                    "early_checkout_refund_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                        verbose_name="Erken Check-out İade Oranı (%)",
                    ),
                ),
                (
                    "auto_checkout_time",
                    models.TimeField(
                        blank=True,
                        help_text="Bu saatten sonra otomatik check-out yapılır",
                        null=True,
                        verbose_name="Otomatik Check-out Saati",
                    ),
                ),
                (
                    "print_receipt_auto",
                    models.BooleanField(
                        default=False, verbose_name="Otomatik Makbuz Yazdır"
                    ),
                ),
                (
                    "print_keycard_auto",
                    models.BooleanField(
                        default=False, verbose_name="Otomatik Anahtar Kartı Yazdır"
                    ),
                ),
                (
                    "require_payment_guarantee",
                    models.BooleanField(
                        default=False, verbose_name="Ödeme Garantisi Zorunlu mu?"
                    ),
                ),
                (
                    "default_guarantee_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("credit_card", "Kredi Kartı"),
                            ("deposit", "Depozito"),
                            ("voucher", "Voucher"),
                        ],
                        max_length=20,
                        verbose_name="Varsayılan Garanti Tipi",
                    ),
                ),
                (
                    "allow_overbooking",
                    models.BooleanField(default=False, verbose_name="Overbooking İzni"),
                ),
                (
                    "max_overbooking_limit",
                    models.IntegerField(
                        default=0,
                        help_text="Oda sayısından fazla rezervasyon limiti",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Maksimum Overbooking Limiti",
                    ),
                ),
                (
                    "auto_generate_reservation_code",
                    models.BooleanField(
                        default=True, verbose_name="Otomatik Rezervasyon Kodu Oluştur"
                    ),
                ),
                (
                    "reservation_code_prefix",
                    models.CharField(
                        default="RES",
                        max_length=10,
                        verbose_name="Rezervasyon Kodu Öneki",
                    ),
                ),
                (
                    "hotel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reception_settings",
                        to="hotels.hotel",
                        verbose_name="Otel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resepsiyon Ayarları",
                "verbose_name_plural": "Resepsiyon Ayarları",
            },
        ),
        migrations.CreateModel(
            name="ReceptionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Başlangıç Zamanı",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bitiş Zamanı"
                    ),
                ),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("morning", "Sabah (06:00-14:00)"),
                            ("evening", "Akşam (14:00-22:00)"),
                            ("night", "Gece (22:00-06:00)"),
                            ("custom", "Özel"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="Vardiya Tipi",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reception_sessions",
                        to="hotels.hotel",
                        verbose_name="Otel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reception_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resepsiyon Oturumu",
                "verbose_name_plural": "Resepsiyon Oturumları",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ReceptionActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("checkin", "Check-in"),
                            ("checkout", "Check-out"),
                            ("booking", "Rezervasyon"),
                            ("payment", "Ödeme"),
                            ("refund", "İade"),
                            ("room_change", "Oda Değişikliği"),
                            ("keycard_created", "Anahtar Kartı Oluşturuldu"),
                            ("keycard_deactivated", "Anahtar Kartı İptal Edildi"),
                        ],
                        max_length=30,
                        verbose_name="İşlem Türü",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Tutar",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reception_activities",
                        to="tenant_core.customer",
                        verbose_name="Müşteri",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="reception.reservation",
                        verbose_name="Rezervasyon",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reception_activities",
                        to="hotels.room",
                        verbose_name="Oda",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="reception.receptionsession",
                        verbose_name="Oturum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resepsiyon İşlemi",
                "verbose_name_plural": "Resepsiyon İşlemleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuickAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Şablon Adı")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("quick_checkin", "Hızlı Check-in"),
                            ("quick_checkout", "Hızlı Check-out"),
                            ("walk_in", "Kapı Müşterisi"),
                            ("group_checkin", "Grup Check-in"),
                        ],
                        max_length=30,
                        verbose_name="İşlem Tipi",
                    ),
                ),
                (
                    "template_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Şablon için varsayılan değerler",
                        verbose_name="Şablon Verileri",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quick_actions",
                        to="hotels.hotel",
                        verbose_name="Otel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hızlı İşlem Şablonu",
                "verbose_name_plural": "Hızlı İşlem Şablonları",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="KeyCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Kart Numarası",
                    ),
                ),
                (
                    "card_code",
                    models.CharField(
                        help_text="Şifreli kod (RFID/NFC için)",
                        max_length=100,
                        verbose_name="Kart Kodu",
                    ),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("room_only", "Sadece Oda"),
                            ("hotel_access", "Otel Genel"),
                            ("full_access", "Tam Erişim"),
                        ],
                        default="room_only",
                        max_length=20,
                        verbose_name="Erişim Seviyesi",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(verbose_name="Geçerlilik Başlangıcı"),
                ),
                ("valid_until", models.DateTimeField(verbose_name="Geçerlilik Bitişi")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_printed",
                    models.BooleanField(default=False, verbose_name="Yazdırıldı mı?"),
                ),
                (
                    "printed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yazdırma Tarihi"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="key_cards",
                        to="tenant_core.customer",
                        verbose_name="Müşteri",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="key_cards",
                        to="hotels.hotel",
                        verbose_name="Otel",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_cards",
                        to="reception.reservation",
                        verbose_name="Rezervasyon",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="key_cards",
                        to="hotels.room",
                        verbose_name="Oda",
                    ),
                ),
                (
                    "room_number",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="key_cards",
                        to="hotels.roomnumber",
                        verbose_name="Oda Numarası",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anahtar Kartı",
                "verbose_name_plural": "Anahtar Kartları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CheckOut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "check_out_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Check-out Tarihi",
                    ),
                ),
                (
                    "is_early_checkout",
                    models.BooleanField(
                        default=False, verbose_name="Erken Check-out mu?"
                    ),
                ),
                (
                    "early_checkout_reason",
                    models.TextField(blank=True, verbose_name="Erken Check-out Nedeni"),
                ),
                (
                    "early_checkout_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Erken Check-out Ücreti",
                    ),
                ),
                (
                    "is_late_checkout",
                    models.BooleanField(
                        default=False, verbose_name="Geç Check-out mu?"
                    ),
                ),
                (
                    "late_checkout_reason",
                    models.TextField(blank=True, verbose_name="Geç Check-out Nedeni"),
                ),
                (
                    "late_checkout_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Geç Check-out Ücreti",
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Toplam Ödenen",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Bakiye",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "checked_out_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="check_outs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Check-out Yapan",
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_out_record",
                        to="reception.reservation",
                        verbose_name="Rezervasyon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Check-out",
                "verbose_name_plural": "Check-out'lar",
                "ordering": ["-check_out_datetime"],
            },
        ),
        migrations.CreateModel(
            name="CheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "check_in_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Check-in Tarihi",
                    ),
                ),
                (
                    "is_early_checkin",
                    models.BooleanField(
                        default=False, verbose_name="Erken Check-in mi?"
                    ),
                ),
                (
                    "early_checkin_reason",
                    models.TextField(blank=True, verbose_name="Erken Check-in Nedeni"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="check_ins",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Check-in Yapan",
                    ),
                ),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in_record",
                        to="reception.reservation",
                        verbose_name="Rezervasyon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Check-in",
                "verbose_name_plural": "Check-in'ler",
                "ordering": ["-check_in_datetime"],
            },
        ),
        migrations.CreateModel(
            name="ReservationUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("created", "Oluşturuldu"),
                            ("updated", "Güncellendi"),
                            ("cancelled", "İptal Edildi"),
                            ("checked_in", "Check-in Yapıldı"),
                            ("checked_out", "Check-out Yapıldı"),
                            ("room_changed", "Oda Değiştirildi"),
                            ("payment_added", "Ödeme Eklendi"),
                            ("refund_added", "İade Eklendi"),
                            ("archived", "Arşivlendi"),
                            ("restored", "Geri Getirildi"),
                        ],
                        max_length=20,
                        verbose_name="Güncelleme Türü",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Alan Adı"
                    ),
                ),
                ("old_value", models.TextField(blank=True, verbose_name="Eski Değer")),
                ("new_value", models.TextField(blank=True, verbose_name="Yeni Değer")),
                ("notes", models.TextField(blank=True, verbose_name="Notlar")),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="reception.reservation",
                        verbose_name="Rezervasyon",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservation_updates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Güncelleyen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rezervasyon Güncelleme",
                "verbose_name_plural": "Rezervasyon Güncellemeleri",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reservation", "update_type"],
                        name="reception_r_reserva_70b8ec_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["hotel", "status", "is_deleted"],
                name="reception_r_hotel_i_3e0652_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["check_in_date", "check_out_date"],
                name="reception_r_check_i_d42d01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["reservation_code"], name="reception_r_reserva_703f43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["customer_email", "customer_phone"],
                name="reception_r_custome_8f0004_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["source", "agency_id", "channel_id"],
                name="reception_r_source_755785_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["is_complimentary"], name="reception_r_is_comp_25edf8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receptionsession",
            index=models.Index(
                fields=["user", "hotel", "is_active"],
                name="reception_r_user_id_bdea10_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receptionactivity",
            index=models.Index(
                fields=["session", "activity_type"],
                name="reception_r_session_d36c11_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receptionactivity",
            index=models.Index(
                fields=["guest", "reservation"], name="reception_r_guest_i_c360d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="keycard",
            index=models.Index(
                fields=["card_number"], name="reception_k_card_nu_6062c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="keycard",
            index=models.Index(
                fields=["customer", "room"], name="reception_k_custome_4a1a3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="keycard",
            index=models.Index(
                fields=["reservation", "is_active"],
                name="reception_k_reserva_445467_idx",
            ),
        ),
    ]
