# Generated by Django 4.2.11 on 2025-11-11 23:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reception", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reception_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Resepsiyon personeli tarafından uygulanan ekstra indirim tutarı",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="Ön Büro İndirim Tutarı",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="reception_discount_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Resepsiyon personeli tarafından uygulanan ekstra indirim oranı",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="Ön Büro İndirim Oranı (%)",
            ),
        ),
    ]
