# Generated by Django 4.2.11 on 2025-11-12 22:41

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('accounting', '0002_invoice_customer'),
        ('channels', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('name', models.CharField(max_length=200, verbose_name='Şablon Adı')),
                ('code', models.SlugField(unique=True, verbose_name='Şablon Kodu')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('template_html', models.TextField(help_text='HTML şablon içeriği', verbose_name='HTML Şablon')),
                ('template_css', models.TextField(blank=True, help_text='Özel CSS stilleri', verbose_name='CSS Stilleri')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan Şablon mu?')),
            ],
            options={
                'verbose_name': 'Voucher Şablonu',
                'verbose_name_plural': 'Voucher Şablonları',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='İptal İade Tutarı'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='İndirim Yüzdesi'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Yüzde'), ('fixed', 'Sabit Tutar')], max_length=20, null=True, verbose_name='İndirim Tipi'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='early_check_in',
            field=models.BooleanField(default=False, help_text='Normal check-in saatinden önce giriş yapıldı', verbose_name='Erken Check-in mi?'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='early_check_in_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Erken Check-in Ücreti'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='İptal Edildi mi?'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_comp',
            field=models.BooleanField(default=False, help_text='Ücretsiz rezervasyon', verbose_name='Comp Rezervasyon mu?'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_manual_price',
            field=models.BooleanField(default=False, help_text='Fiyat manuel olarak girildi mi?', verbose_name='Manuel Fiyat mı?'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_no_show',
            field=models.BooleanField(default=False, help_text='Rezervasyon yapıp gelmeyen misafir', verbose_name='No-Show mu?'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='late_check_out',
            field=models.BooleanField(default=False, help_text='Normal check-out saatinden sonra çıkış yapıldı', verbose_name='Geç Check-out mu?'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='late_check_out_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Geç Check-out Ücreti'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='no_show_reason',
            field=models.TextField(blank=True, verbose_name='No-Show Nedeni'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_agent',
            field=models.ForeignKey(blank=True, help_text='Rezervasyonu yapan acente (varsa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='sales.agency', verbose_name='Rezervasyon Acentesi'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_channel',
            field=models.ForeignKey(blank=True, help_text='Booking.com, Expedia vb. (varsa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='channels.channel', verbose_name='Rezervasyon Kanalı'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen Kullanıcı'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='currency',
            field=models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='TRY', max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gecelik oda fiyatı', max_digits=10, verbose_name='Oda Fiyatı'),
        ),
        migrations.CreateModel(
            name='ReservationVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('voucher_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Voucher Kodu')),
                ('voucher_data', models.JSONField(blank=True, default=dict, help_text='Şablon için veri', verbose_name='Voucher Verileri')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Gönderildi mi?')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Tarihi')),
                ('sent_via', models.CharField(blank=True, choices=[('email', 'E-posta'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=20, verbose_name='Gönderim Yöntemi')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='reception.reservation', verbose_name='Rezervasyon')),
                ('voucher_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='reception.vouchertemplate', verbose_name='Voucher Şablonu')),
            ],
            options={
                'verbose_name': 'Rezervasyon Voucher',
                'verbose_name_plural': "Rezervasyon Voucher'ları",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reservation'], name='reception_r_reserva_4da189_idx'), models.Index(fields=['voucher_code'], name='reception_r_voucher_351572_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReservationTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('action_type', models.CharField(choices=[('created', 'Oluşturuldu'), ('updated', 'Güncellendi'), ('checkin', 'Check-in Yapıldı'), ('checkout', 'Check-out Yapıldı'), ('payment', 'Ödeme Eklendi'), ('cancelled', 'İptal Edildi'), ('no_show', 'No-Show İşaretlendi'), ('comp', 'Comp Olarak İşaretlendi'), ('status_changed', 'Durum Değişti')], max_length=50, verbose_name='İşlem Tipi')),
                ('action_description', models.TextField(blank=True, verbose_name='İşlem Açıklaması')),
                ('old_value', models.JSONField(blank=True, default=dict, help_text='Değişiklik öncesi değerler', verbose_name='Eski Değer')),
                ('new_value', models.JSONField(blank=True, default=dict, help_text='Değişiklik sonrası değerler', verbose_name='Yeni Değer')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='reception.reservation', verbose_name='Rezervasyon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_timeline_actions', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Rezervasyon Zaman Çizelgesi',
                'verbose_name_plural': 'Rezervasyon Zaman Çizelgeleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reservation', 'action_type'], name='reception_r_reserva_951aea_idx'), models.Index(fields=['created_at'], name='reception_r_created_9d0e14_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReservationPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Silinmiş mi?')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi')),
                ('payment_date', models.DateField(default=datetime.date.today, verbose_name='Ödeme Tarihi')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ödeme Tutarı')),
                ('payment_method', models.CharField(choices=[('cash', 'Nakit'), ('credit_card', 'Kredi Kartı'), ('debit_card', 'Banka Kartı'), ('transfer', 'Havale/EFT'), ('check', 'Çek'), ('other', 'Diğer')], max_length=20, verbose_name='Ödeme Yöntemi')),
                ('payment_type', models.CharField(choices=[('advance', 'Ön Ödeme'), ('full', 'Tam Ödeme'), ('partial', 'Kısmi Ödeme'), ('refund', 'İade')], max_length=20, verbose_name='Ödeme Tipi')),
                ('currency', models.CharField(default='TRY', max_length=3, verbose_name='Para Birimi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('receipt_no', models.CharField(blank=True, max_length=50, verbose_name='Fiş No')),
                ('accounting_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_payments', to='accounting.payment', verbose_name='Muhasebe Ödemesi')),
                ('cash_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_payments', to='finance.cashtransaction', verbose_name='Kasa İşlemi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reservation_payments', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan Kullanıcı')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reception.reservation', verbose_name='Rezervasyon')),
            ],
            options={
                'verbose_name': 'Rezervasyon Ödemesi',
                'verbose_name_plural': 'Rezervasyon Ödemeleri',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['reservation', 'payment_date'], name='reception_r_reserva_10d84b_idx'), models.Index(fields=['payment_method'], name='reception_r_payment_56a6d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReservationGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('guest_type', models.CharField(choices=[('adult', 'Yetişkin'), ('child', 'Çocuk')], max_length=20, verbose_name='Misafir Tipi')),
                ('guest_order', models.IntegerField(default=1, help_text='Misafir sırası (1, 2, 3...)', verbose_name='Misafir Sırası')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Erkek'), ('female', 'Kadın'), ('other', 'Diğer')], max_length=10, verbose_name='Cinsiyet')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('age', models.IntegerField(blank=True, help_text='Çocuklar için yaş bilgisi', null=True, verbose_name='Yaş')),
                ('tc_no', models.CharField(blank=True, max_length=11, verbose_name='TC Kimlik No')),
                ('passport_no', models.CharField(blank=True, max_length=50, verbose_name='Pasaport No')),
                ('passport_serial_no', models.CharField(blank=True, max_length=20, verbose_name='Pasaport Seri No')),
                ('id_serial_no', models.CharField(blank=True, help_text='TC Kimlik seri no', max_length=20, verbose_name='Kimlik Seri No')),
                ('nationality', models.CharField(default='Türkiye', max_length=100, verbose_name='Vatandaşlık')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='reception.reservation', verbose_name='Rezervasyon')),
            ],
            options={
                'verbose_name': 'Rezervasyon Misafiri',
                'verbose_name_plural': 'Rezervasyon Misafirleri',
                'ordering': ['reservation', 'guest_type', 'guest_order'],
                'indexes': [models.Index(fields=['reservation', 'guest_type'], name='reception_r_reserva_5b1645_idx'), models.Index(fields=['tc_no'], name='reception_r_tc_no_e53069_idx'), models.Index(fields=['passport_no'], name='reception_r_passpor_a69fa6_idx')],
            },
        ),
    ]
