# Generated by Django 4.2.11 on 2025-11-13 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reception', '0002_vouchertemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Silen Kullanıcı'),
        ),
    ]
