# Generated by Django 4.2.11 on 2025-11-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reception", "0002_reservation_reception_discount_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="total_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Rezervasyon için ödenen toplam tutar",
                max_digits=10,
                verbose_name="Toplam Ödenen",
            ),
        ),
    ]
