# Generated by Django 4.2.11 on 2025-11-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotelextraservice'),
        ('settings', '0003_emailgateway_emailtemplate_emailsentlog_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailgateway',
            name='settings_em_is_defa_4c766a_idx',
        ),
        migrations.RemoveIndex(
            model_name='smsgateway',
            name='settings_sm_is_defa_c4414f_idx',
        ),
        migrations.AddField(
            model_name='emailgateway',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Boş bırakılırsa tüm oteller için genel gateway olur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_gateways', to='hotels.hotel', verbose_name='Otel'),
        ),
        migrations.AddField(
            model_name='smsgateway',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Boş bırakılırsa tüm oteller için genel gateway olur', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_gateways', to='hotels.hotel', verbose_name='Otel'),
        ),
        migrations.AlterField(
            model_name='emailgateway',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Otel bazlı varsayılan gateway (her otel için ayrı olabilir)', verbose_name='Varsayılan Gateway mi?'),
        ),
        migrations.AddIndex(
            model_name='emailgateway',
            index=models.Index(fields=['hotel', 'is_default'], name='settings_em_hotel_i_1fcc47_idx'),
        ),
        migrations.AddIndex(
            model_name='emailgateway',
            index=models.Index(fields=['hotel', 'is_active'], name='settings_em_hotel_i_cf8d72_idx'),
        ),
        migrations.AddIndex(
            model_name='smsgateway',
            index=models.Index(fields=['hotel', 'is_default'], name='settings_sm_hotel_i_8ca9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='smsgateway',
            index=models.Index(fields=['hotel', 'is_active'], name='settings_sm_hotel_i_5b28d6_idx'),
        ),
    ]
