# Generated by Django 4.2.11 on 2025-11-10 20:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Sağlayıcı Adı"),
                ),
                ("code", models.SlugField(unique=True, verbose_name="Kod")),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("email", "E-posta"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=20,
                        verbose_name="Sağlayıcı Tipi",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("api_url", models.URLField(blank=True, verbose_name="API URL")),
                (
                    "test_api_url",
                    models.URLField(blank=True, verbose_name="Test API URL"),
                ),
                (
                    "supports_bulk",
                    models.BooleanField(
                        default=False, verbose_name="Toplu Gönderim Destekli"
                    ),
                ),
                (
                    "supports_template",
                    models.BooleanField(default=True, verbose_name="Şablon Destekli"),
                ),
                (
                    "supports_unicode",
                    models.BooleanField(
                        default=True, verbose_name="Türkçe Karakter Destekli"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_test_mode",
                    models.BooleanField(default=True, verbose_name="Test Modu"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="Sıralama")),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="API endpoint'leri, parametreler vb.",
                        verbose_name="Sağlayıcı Ayarları",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim Sağlayıcı",
                "verbose_name_plural": "Bildirim Sağlayıcıları",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Silinmiş mi?"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Silinme Tarihi"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Şablon Adı")),
                ("code", models.SlugField(unique=True, verbose_name="Şablon Kodu")),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("email", "E-posta"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=20,
                        verbose_name="Şablon Tipi",
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("payment_success", "Ödeme Başarılı"),
                            ("payment_failed", "Ödeme Başarısız"),
                            ("payment_pending", "Ödeme Beklemede"),
                            ("subscription_created", "Abonelik Oluşturuldu"),
                            ("subscription_renewed", "Abonelik Yenilendi"),
                            ("subscription_expiring", "Abonelik Sona Eriyor"),
                            ("subscription_expired", "Abonelik Sona Erdi"),
                            ("package_purchased", "Paket Satın Alındı"),
                            ("package_upgraded", "Paket Yükseltildi"),
                            ("package_downgraded", "Paket Düşürüldü"),
                            ("user_created", "Kullanıcı Oluşturuldu"),
                            ("user_password_reset", "Şifre Sıfırlama"),
                            ("user_login", "Kullanıcı Girişi"),
                            ("reminder_payment_due", "Ödeme Vadesi Hatırlatması"),
                            (
                                "reminder_subscription_expiring",
                                "Abonelik Sona Eriyor Hatırlatması",
                            ),
                            (
                                "reminder_trial_ending",
                                "Deneme Süresi Bitiyor Hatırlatması",
                            ),
                            ("custom", "Özel"),
                        ],
                        max_length=50,
                        verbose_name="Tetikleyici Olay",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Email ve WhatsApp için",
                        max_length=200,
                        verbose_name="Konu",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Şablon içeriği ({{variable}} formatında)",
                        verbose_name="İçerik",
                    ),
                ),
                (
                    "content_html",
                    models.TextField(
                        blank=True,
                        help_text="Email için HTML formatında",
                        verbose_name="HTML İçerik",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_system",
                    models.BooleanField(
                        default=False,
                        help_text="Sistem şablonları silinemez",
                        verbose_name="Sistem Şablonu",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Yüksek öncelik önce gönderilir",
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Şablonda kullanılabilecek değişkenler ve açıklamaları",
                        verbose_name="Kullanılabilir Değişkenler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim Şablonu",
                "verbose_name_plural": "Bildirim Şablonları",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="NotificationProviderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API Key"
                    ),
                ),
                (
                    "api_secret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="API Secret"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Kullanıcı Adı"
                    ),
                ),
                (
                    "password",
                    models.CharField(blank=True, max_length=255, verbose_name="Şifre"),
                ),
                (
                    "sender_id",
                    models.CharField(
                        blank=True,
                        help_text="SMS için gönderen numara, Email için gönderen adres",
                        max_length=50,
                        verbose_name="Gönderen ID",
                    ),
                ),
                (
                    "whatsapp_business_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="WhatsApp Business ID"
                    ),
                ),
                (
                    "whatsapp_phone_number_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="WhatsApp Phone Number ID",
                    ),
                ),
                (
                    "whatsapp_access_token",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="WhatsApp Access Token"
                    ),
                ),
                (
                    "whatsapp_verify_token",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="WhatsApp Verify Token"
                    ),
                ),
                (
                    "sms_username",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="SMS Kullanıcı Adı"
                    ),
                ),
                (
                    "sms_password",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="SMS Şifre"
                    ),
                ),
                (
                    "sms_header",
                    models.CharField(
                        blank=True,
                        help_text="SMS gönderen başlığı (max 11 karakter)",
                        max_length=11,
                        verbose_name="SMS Başlık",
                    ),
                ),
                (
                    "email_host",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="SMTP Host"
                    ),
                ),
                (
                    "email_port",
                    models.IntegerField(
                        default=587,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="SMTP Port",
                    ),
                ),
                (
                    "email_use_tls",
                    models.BooleanField(default=True, verbose_name="TLS Kullan"),
                ),
                (
                    "email_use_ssl",
                    models.BooleanField(default=False, verbose_name="SSL Kullan"),
                ),
                (
                    "email_from",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Gönderen E-posta"
                    ),
                ),
                (
                    "email_from_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Gönderen Adı"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktif mi?"),
                ),
                (
                    "is_test_mode",
                    models.BooleanField(default=True, verbose_name="Test Modu"),
                ),
                (
                    "total_sent",
                    models.IntegerField(default=0, verbose_name="Toplam Gönderim"),
                ),
                (
                    "total_failed",
                    models.IntegerField(default=0, verbose_name="Toplam Başarısız"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Kullanım"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Ek Ayarlar"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configs",
                        to="notifications.notificationprovider",
                        verbose_name="Sağlayıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim Sağlayıcı Yapılandırması",
                "verbose_name_plural": "Bildirim Sağlayıcı Yapılandırmaları",
                "ordering": ["provider", "-is_active"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("email", "E-posta"),
                            ("phone", "Telefon"),
                            ("user", "Kullanıcı"),
                        ],
                        max_length=20,
                        verbose_name="Alıcı Tipi",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Alıcı E-posta"
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Alıcı Telefon"
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Alıcı Adı"
                    ),
                ),
                (
                    "subject",
                    models.CharField(blank=True, max_length=200, verbose_name="Konu"),
                ),
                ("content", models.TextField(verbose_name="İçerik")),
                (
                    "content_html",
                    models.TextField(blank=True, verbose_name="HTML İçerik"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Beklemede"),
                            ("sent", "Gönderildi"),
                            ("failed", "Başarısız"),
                            ("delivered", "Teslim Edildi"),
                            ("read", "Okundu"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gönderim Tarihi"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Teslim Tarihi"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Okunma Tarihi"
                    ),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Sağlayıcı Yanıtı"
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Sağlayıcı Mesaj ID"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Hata Mesajı"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="Tekrar Deneme Sayısı"),
                ),
                (
                    "related_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="İlişkili Model"
                    ),
                ),
                (
                    "related_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="İlişkili ID"
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="notifications.notificationprovider",
                        verbose_name="Sağlayıcı",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="notifications.notificationtemplate",
                        verbose_name="Şablon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim Log",
                "verbose_name_plural": "Bildirim Logları",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="notificatio_status_68c9bc_idx",
                    ),
                    models.Index(
                        fields=["recipient_email"],
                        name="notificatio_recipie_e7d489_idx",
                    ),
                    models.Index(
                        fields=["recipient_phone"],
                        name="notificatio_recipie_9f19f3_idx",
                    ),
                ],
            },
        ),
    ]
